feat: Liquor 엔티티 재설계
woowatechcamp/soolsool pull request #127
Opened 2023-08-24 04:38 UTC by whatasame

## ♻️ 변경 사항

Liquor에서 재고를 별도의 테이블로 분리

<br>

## 📌 참고 사항

노출 대비 클릭률은 #126 에서 진행한다.

<br>

## 🎸 기타

closes #123

2023-08-24 12:58 UTC, jjungsk requested changes
test 와 추가 push는 집 가서 바로 볼게요^^

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/code/LiquorStockErrorCode.java
> +    NOT_ENOUGH_LIQUOR_STOCKS(BAD_REQUEST.value(), "LS103", "주류 재고가 부족합니다."),
LS101 : 동일한 주류가 아닌 재고가 포함 이랑
LS102 = LS103 같은 의미인것 같은데 message로 잘 이해가 안갑니다ㅜ

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorStockController.java
> +        liquorStockService.saveLiquorStock(request);
변수명 이름을 단순 request보다는 의미가 드러나도 좋을것 같숩니다^^

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/Liquor.java
> +    }
역할 분리 좋아연~

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorStock.java
> +    }
얘도 VO객체로 정의하긴 했지만 message 던져서 감소하는 것도 좋은 방법일 것 같숩니다

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorStocks.java
> +    }
깔끔한것 같긴한데 TODO 를 왜 남겨놓은지 알것만 같은.. 낭만 7.8프로 정도 부족하긴 하네요

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorStockService.java
> +    public void decreaseLiquorStock(final Long liquorId, int quantity) {
+ final ^^

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/order/service/OrderService.java
> +            .build();
!???

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/payment/domain/Payment.java
> +    private String cardMid; // 카드사 가맹점번호
원시값 포장 ㄷㄷ..

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/dto/response/KakaoPayApproveResponse.java
> +public class KakaoPayApproveResponse {
@Data~~

2023-08-24 12:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +    }
이거 method 빼신 이유가 뭐가 있을까요??

2023-08-24 15:47 UTC, jjungsk reviewed
테스트 코드 구우욷~!!

2023-08-24 15:47 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/core/payment/infra/FakePayClient.java
> +            "http://지들끼리이야기하는URL"
^^
이해하기 쉽도록
"성공 url"
"실패 url" 이런식으로 인자값이 뭐가 들어가는지 설명해도 좋을것 같아요^^

2023-08-24 15:47 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/core/payment/infra/FakePayClient.java
> +@Component
단순 궁금 사항입니다
@Primary annotaion이 없으면 빈을 찾지 못하는 예외 사항이 발생했나요??

2023-08-24 16:20 UTC, worldii approved these changes
와오 수고 많으셨어요 똥 처리하느라 고생하셨네요!!!

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorStocks.java
> +    public void decreaseStock(int quantity) {
final !!

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorStocks.java
> +            .orElse(0);
```suggestion
       final int totalStock = liquorStocks.stream()
                            .mapToInt(LiquorStock::getStock)
                            .sum();
```
조금더 직관적이게 바꾸면 좋을꺼 같아요! 아니면 for문도 좋고요!

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +    @Transactional
위치를 public 쪽인 위쪽으로 올릴수 있을까요?? 아래에 있는 type과 관련된 메서드 들은 부가적인 요소라고 판단이 되네요!!

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorStockService.java
> +    public Long saveLiquorStock(final LiquorStockSaveRequest request) {
request도 네이밍 잘 해주면 좋겠어여!

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/order/service/OrderService.java
> +            .build();
saveOrder와 addOrder 둘다 쓰이는 건가요?

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/order/service/OrderService.java
> +            .findByType(COMPLETED)
getOrderStatusByType 프라이빗 메서드 활용하는 건 어떨까요?

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/receipt/domain/ReceiptItem.java
>      public static ReceiptItem of( // 생성자로 바꾸기
주석 todo 리스트 인가요?

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/dto/response/KakaoPayApproveResponse.java
> +            card_info.getPurchase_corp(),
혹시 카드 null 처리 하셨나요?? 머니 로 계산했을때 나타나는 에러요

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/dto/response/KakaoPayApproveResponse.java
> +    private String payment_method_type;
이거는 파이널 어쩔수없는 부분인가요?

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/service/KakaoPayService.java
> +    public Long approve(final Long memberId, final Long receiptId, final String pgToken) {
하나는 페이 레디고 하나는 approve 네요? 일관되게 네이밍 갖는 건 어떨까요?

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/order/service/OrderService.java
> +        Order.builder()
로직이 두번 중복되네요

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/KakaoPayClient.java
>          MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
이거도 파이널 가능한가요?

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/KakaoPayClient.java
>          MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
파람스를 에드하고 반환하는 과정을 private 메서드로 뺄수 있나요?

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/KakaoPayClient.java
> +            return kakaoPayApproveResponse.toPayApproveResponse();
머니로 계산할때 에러 처리해야 할거같아요!

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/KakaoPayClient.java
>          MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
payApprove 부분도 파이널 신경써 주세요!

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/service/KakaoPayService.java
> +public class KakaoPayService {
카카오 페이에서는 kakaoPayClient를 쓸텐데, payClient 를 interface화 시킨 장점이 없어지는 것 같아 보이기도 하네요

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/service/KakaoPayService.java
> +        final Receipt receipt = receiptService
receipt에서 단순히 데이터 값을 가져오는 거면 receiptRepository를 써도 된다고 생각이 들었는데, 어떻게 생각하시나요?

2023-08-24 16:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +    }
저도 궁금

2023-08-25 01:08 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorStockController.java
> +        liquorStockService.saveLiquorStock(request);
전체 이름을 쓰다보면 코드가 너무 길어지고 자료형으로 의미를 알 수 있어서 줄였는데 바꾸는게 좋을까요?

2023-08-25 01:08 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/code/LiquorStockErrorCode.java
> +    NOT_ENOUGH_LIQUOR_STOCKS(BAD_REQUEST.value(), "LS103", "주류 재고가 부족합니다."),
null과 0의 차이인 것 같은데 조금 더 명확하게 수정해봤어요.

2023-08-25 01:09 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +    @Transactional
올렸씁니다

2023-08-25 01:11 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/payment/domain/Payment.java
> +    private String cardMid; // 카드사 가맹점번호
아마 못할것 같아요..

2023-08-25 01:32 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +    }
두 군데서 사용해서 뺐는데 한 곳에서 밖에 안 쓰네요. 다시 합쳤슴다

2023-08-25 02:16 UTC, whatasame reviewed
반영햇습니다..

2023-08-25 02:16 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorStocks.java
> +    public void decreaseStock(int quantity) {
재고 감소 로직 때 중간에 값을 변경해야해서 final을 뺐습니다 ㅠ

2023-08-25 02:16 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/KakaoPayClient.java
>          MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
부탁합니다..

2023-08-25 02:27 UTC, jjungsk reviewed
재휘 정규 고생 많으셨습니다^^

2023-08-25 02:27 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorStockController.java
> +        liquorStockService.saveLiquorStock(request);
개인 취향인 부분이라 제 의견을 말해 보았숩니다^^

2023-08-25 02:38 UTC, worldii approved these changes
수고 넘 많았습니다~!~!

2023-08-25 02:38 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorStocks.java
> +    public void decreaseStock(int quantity) {
아항

2023-08-25 02:38 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorStocksTest.java
> +            .hasMessage("주류 재고가 존재하지 않습니다.");
LiquorStockErrorCode. * ~ .getMessage() 로 쓰는 것은 어떨까요?

2023-08-25 02:45 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/order/service/OrderService.java
> +            .build();
삭제했습니다~

2023-08-25 02:47 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/payment/infra/FakePayClient.java
> +@Component
PayClient가 prod에도 있고 test에도 있어서 어떤 빈을 사용해야할 지 몰라서 예외가 발생해요.

2023-08-25 02:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/domain/ReceiptItem.java
>      public static ReceiptItem of( // 생성자로 바꾸기
삭제했습니다~

2023-08-25 02:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/payment/infra/dto/response/KakaoPayApproveResponse.java
> +            card_info.getPurchase_corp(),
처리완료

2023-08-25 02:52 UTC, jjungsk approved these changes

2023-08-25 02:56 UTC, merged