feat: 캐쉬 성능 개선
woowatechcamp/soolsool pull request #135
Opened 2023-08-25 11:21 UTC by worldii

## ♻️ 변경 사항

- 카테고리 캐쉬 저장하여 성능 개선
- CartItem 서비스의 findAllByMemberId  쿼리에서,  left outer join을 inner join 으로 바꿔 속도 개선

<br>

## 📌 참고 사항

```
ex)
* 결제 부분 로직이 복잡한데, ~~~ 이유로 ~~~ 를 구현하기 위해 불가피했읍니다.
* ...
```

<br>

## 🎸 기타

closes #130

2023-08-26 04:12 UTC, jjungsk commented
dev ddl-auto : none인지 확인 부탁드려요~ 아니라면 none으로 수정 부탁!!

2023-08-26 09:55 UTC, worldii commented
했어여!

2023-08-26 12:57 UTC, hwihwi523 requested changes
짱!!

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +        if (brewType == null) {
`Objects.isNull(~~~Type)`은 어떤가요???
그가.. 그가 찾아옵니다..

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/member/repository/MemberRoleCache.java
> +@Component
```suggestion
@Component
@RequiredArgsConstructor
```

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/member/service/MemberService.java
> +        if (memberRoleType == null) {
```suggestion
        if (Objects.isNull(memberRoleType)) {
```

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/repository/ReceiptStatusCache.java
> +}
```suggestion
    }
}
```

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/global/common/CacheType.java
> +    LIQUOR_STATUS("liquorStatus", 10, 100),
```suggestion
public enum CacheType {

    LIQUOR_STATUS("liquorStatus", 10, 100),
```

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/global/common/CacheType.java
> +    RECEIPT_STATUS("receiptStatus", 10, 100);
```suggestion
    RECEIPT_STATUS("receiptStatus", 10, 100),
    ;
```

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/global/common/CacheType.java
> +    }
@RequiredArgsConstructor 쓰는 건 어뗘요???

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/global/config/CaffeineCacheConfig.java
> +        SimpleCacheManager cacheManager = new SimpleCacheManager();
```suggestion
        final SimpleCacheManager cacheManager = new SimpleCacheManager();
```

2023-08-26 12:57 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/global/config/CaffeineCacheConfig.java
> +        List<CaffeineCache> caches = Arrays.stream(CacheType.values()).map(
```suggestion
        final List<CaffeineCache> caches = Arrays.stream(CacheType.values()).map(
```

2023-08-26 12:57 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/cart/repository/CartItemRepositoryTest.java
> +        final List<CartItem> allByMemberId = cartItemRepository.findAllByMemberId(1L);
```suggestion
        List<CartItem> allByMemberId = cartItemRepository.findAllByMemberId(1L);
```

2023-08-26 12:57 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/cart/repository/CartItemRepositoryTest.java
>  }
```suggestion
        stopWatch.stop();
        
        assertThat(allByMemberId).isNotEmpty();
    }
}
```

2023-08-26 13:33 UTC, whatasame reviewed
고생하셨스빈다

2023-08-26 13:33 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +        if (brewType == null) {
흠..

2023-08-26 13:33 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/cart/repository/CartItemRepositoryTest.java
>  }
given when then절로 해주세요~

2023-08-26 16:22 UTC, jjungsk approved these changes
Cache 적용 너무 좋아요^^

2023-08-26 16:22 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +}
LiquorBrewCache 클래스를 추가적으로 생성한 이유가 있나요??
interface 에서 필요한 class에 대해서만 @Cacheable 을 통해 해당값을 가져와도 좋을것 같숩니다!

2023-08-26 16:22 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/order/repository/OrderStatusRepository.java
> +    @Cacheable(value = "orderStatus", key = "#type")
OrderStatusCache 클래스 대신 얘만 남겨둬도 괜찮을것 같아요!

2023-08-26 16:22 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/global/config/CaffeineCacheConfig.java
> +        List<CaffeineCache> caches = Arrays.stream(CacheType.values()).map(
final 귀신이네 개 잘찾는다잉 ㅋㅋㅋ

2023-08-26 16:24 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/global/common/CacheType.java
> +    RECEIPT_STATUS("receiptStatus", 10, 100);
와오 진짜 짱

2023-08-26 16:24 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/global/common/CacheType.java
> +    }
와오 킹왕짱

2023-08-26 16:25 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/global/config/CaffeineCacheConfig.java
> +        SimpleCacheManager cacheManager = new SimpleCacheManager();
와오

2023-08-26 16:27 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/core/cart/repository/CartItemRepositoryTest.java
>  }
음 성능테스트 그냥 없앨까요? stopwatch 가 프린트할라고 찍을라고 한거거등요

2023-08-26 16:47 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +}
음 처음에 널값 때문에 고생을 했었는데, 검색을 담당하는 brew, region, status 에 대해서는 null 값이 들어올 수 있기 때문에 이를 잘 모르는 개발자라면, 네이밍으로서 방지해주고 싶어서 저렇게 구현한게 컸습니다. 그리고 프록시가 public 메서드 단위에서만 적용되는 것으로 알고 있는데 interface에 대해서 적용이 되는가도 의문이 들었습니다.

2023-08-26 16:48 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +}
해당 질문에 관하여 저도 헷갈려서 찾아봤는데 공식문서에서도 interface 에서 캐쉬 어노테이션을 사용할 수 있지만, 권장하지 않는 다고 나와있네요!!  좋은 질문 주셔서 감사합니다! 

https://docs.spring.io/spring-framework/docs/3.1.x/spring-framework-reference/html/cache.html

2023-08-26 16:58 UTC, worldii commented
리뷰 고쳤습니다!!!

2023-08-26 17:02 UTC, whatasame reviewed
빠른 리뷰 반영 종하요

2023-08-26 17:02 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/cart/repository/CartItemRepositoryTest.java
>  }
아뇨 좋은디유? 안 없애도 될 것 같아요

2023-08-26 17:02 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/config/CaffeineCacheConfig.java
> +        List<CaffeineCache> caches = Arrays.stream(CacheType.values()).map(
ㅋㅋㅋㅋ

2023-08-26 17:03 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +}
오호 interface 자체에는 아마 proxy 가 Java 의 default 인 Dynamic proxy 로 동작하는데 아마 JPA interface 구현체에 정의할 경우 해당 @Cache annotaion이 개발자 의도대로 적용이 되지 않아서 concrete class에 정의하라 하는것 같네요! 저도 덕분에 배웠습니다^^

2023-08-26 17:19 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/order/repository/OrderStatusRepository.java
> +    @Cacheable(value = "orderStatus", key = "#type")
음? 얘는 왜 OrderStatusCache와 OrderStatusRepository가 공존하나요?

2023-08-26 17:19 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +}
interface에 달아놓은 annotation이 상속되지 않으므로 이를 구현한 proxy에서 인식할 수 없다는 건가요? 그럼 class based proxies는 뭘까요? interface based proxy도 있나용?

2023-08-26 17:32 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/order/repository/OrderStatusRepository.java
> +    @Cacheable(value = "orderStatus", key = "#type")
그르게여 해당 부분 고칠게요 ㅠㅠ

2023-08-26 17:32 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/order/repository/OrderStatusRepository.java
> +    @Cacheable(value = "orderStatus", key = "#type")
캐쉬 만들어놓고 여기도 만들었네

2023-08-26 19:01 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +}
오 왤캐 어려워 머리 아픕니다... 멀고 험난한 스프링의 세계.. 낼 정리다시 해보겟읍니다...

2023-08-27 10:39 UTC, hwihwi523 approved these changes
짱!!

2023-08-27 10:39 UTC, merged

2023-09-16 19:36 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +}
전에 몰랐는데 spring aop 에 대해서 이제야 탐구를 해서 알게되었습니다.. 
인터페이스를 통해, 프록시 객체를 생성하는 JDK proxy (interface based proxy) 와 구현체를 통해 프록시 객체를 생성하는 class based proxy인 CGLIB proxy가 있습니다. 스프링은 proxyTargetClass=true 로 해주어서 기본적으로 인터페이스 또한 CGLIB prox로 만들어 준다고 합니다. 자세히는 원리는 모르지만 JDK proxy 같은 경우, 의존 관계 주입을 할 때 구체 클래스 주입이 불가능하지만 CGLIB는 가능하다고 합니다. 이런 문제점을 예방하기 위해서 interface에다가는 위험하니 달지 말라고 하는 것 같습니다.