feat: 결제 수단 기능 추가, 카카오페이 로직 리팩토링
woowatechcamp/soolsool pull request #150
Opened 2023-08-26 17:50 UTC by hwihwi523

## ♻️ 변경 사항

1. 결제 수단 기능 추가
    - Payment 엔티티 이름을 PaymentInfo로 변경했습니다.
    - 아래와 같은 이유로 PaymentInfo 엔티티를 order 도메인으로 이동시켰습니다.
        1. payment 도메인은 결제 로직만을 담당한다고 생각했습니다.
        2. 결제 정보란 주문 내역에 포함되는 것이라 생각했습니다.
        3. PaymentInfo가 payment 도메인에 있다면, 주문 내역을 조회하기 위해 order -> payment를 의존하게 되고, 의존성에 싸이클이 생깁니다.
2. 카카오페이 로직 리팩토링
    - Map을 사용해 body를 생성하는 부분을 메서드로 분리했습니다.
    - try-catch 구문을 삭제하고, RestClientException을 GlobalExceptionHandler가 담당하도록 했습니다.
    - 카카오페이로 요청을 보내고, 요청값에 따라 예외를 던지는 부분을 메서드로 분리했습니다.

<br>

## 📌 참고 사항 

<br>

## 🎸 기타

```
ex) 닫을 이슈가 있다면,
closes #이슈번호
```
closes #146, closes #148

2023-08-26 18:05 UTC, whatasame requested changes
테스트가 없는게 조금 아쉽네요!

2023-08-26 18:05 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/order/domain/PaymentInfo.java
> +public class PaymentInfo {
Order에 종속적인 느낌을 주기 위하여 `OrderPaymentInfo`는 어떨까요?

2023-08-26 18:05 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/order/repository/PaymentInfoRepository.java
> +}
테스트 작성해주세요!

2023-08-27 06:20 UTC, worldii approved these changes
수고하셨습니다~!~!

2023-08-27 06:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/order/service/OrderService.java
> +    private final PaymentInfoRepository paymentInfoRepository;
이거도 패키지가 order에 있는데 paymentInfo 라고 하면 헷갈릴거같아요 네이밍을 통해서 order에 종속적인 느낌을 주면 좋을거같아요

2023-08-27 06:38 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/order/domain/PaymentInfo.java
> +public class PaymentInfo {
너무 불편했는데 와방 좋습니다..

2023-08-27 07:55 UTC, whatasame approved these changes
고슴둥

2023-08-27 08:09 UTC, merged