feat: 클릭률 구현
woowatechcamp/soolsool pull request #152
Opened 2023-08-26 20:56 UTC by whatasame

## ♻️ 변경 사항

*  liquor_ctr 엔티티 구현
* 상품 목록 조회 시 노출 수를 1 증가한다.
* 상품 상세정보 조회 시 클릭 수를 1 증가한다.
* 클릭률 조회 endpoint 구현

<br>

## 📌 참고 사항

<br>

## 🎸 기타

closes #147

2023-08-26 21:06 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtr.java
> +@Table(name = "liquor_ctrs")
liquor_ctr 테이블 이름을 liquor_ctrs로 변경했는데 괜찮나요?

2023-08-27 07:48 UTC, hwihwi523 requested changes
클릭수, 노출수 처리할 때 락 관련된 것 말고는 별 다른 건 업스요잉!!

2023-08-27 07:48 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorCtrRepository.java
> +    List<LiquorCtr> findAllByLiquorIdIn(List<Long> liquorIds);
락을 걸지 않고 조회하면 클릭수나 조회수가 제대로 반영되지 않을 수 있지 않을까여???

2023-08-27 07:48 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/acceptance/LiquorCtrAcceptanceTest.java
> +        final LiquorCtrDetailResponse response = RestAssured
```suggestion
        RestLiquorFixture.술_상세_조회(새로);

        /* when */
        LiquorCtrDetailResponse response = RestAssured
```

2023-08-27 07:48 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/LiquorCtrRepositoryTest.java
> +        final LiquorCtr liquorCtr = liquorCtrRepository.findByLiquorId(새로)
```suggestion
        LiquorCtr liquorCtr = liquorCtrRepository.findByLiquorId(새로)
```

2023-08-27 07:48 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/LiquorCtrRepositoryTest.java
> +        final List<LiquorCtr> liquorCtrs = liquorCtrRepository.findAllByLiquorIdIn(술_목록);
```suggestion
        List<LiquorCtr> liquorCtrs = liquorCtrRepository.findAllByLiquorIdIn(술_목록);
```

2023-08-27 07:57 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorCtrRepository.java
> +    List<LiquorCtr> findAllByLiquorIdIn(List<Long> liquorIds);
PESSIMISTIC_LOCK 이 맞을것 같숩니다!

2023-08-28 01:57 UTC, worldii approved these changes
수고하셨습니다~!

2023-08-28 01:57 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
> +    public double getLiquorCtrByLiquorId(final Long liquorId) {
@Transactional(readonlny= true)!

2023-08-28 05:40 UTC, hwihwi523 approved these changes
굳뜨!!

2023-08-28 05:40 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorCtrRepository.java
> +    List<LiquorCtr> findAllByLiquorIdInWithPessimisticWriteLock(List<Long> liquorIds);
인자 final!!!

2023-08-28 05:45 UTC, merged