refactor: 캐쉬 리팩터링
woowatechcamp/soolsool pull request #213
Opened 2023-09-12 16:09 UTC by worldii

## ♻️ 변경 사항

```
ex)
### docs: PULL_REQUEST_TEMPLATE.md 작성 ... [a6684f7](https://github.com/five-uys/test/commit/7625214be558f7496cca1dec633f02942799dff1)

* PR 생성 시 자동으로 적용될 템플릿
* ...
```

<br>

## 📌 참고 사항

캐쉬의 값이 Null value일때는 unless 조건을, 캐쉬의 키가 Null 일때 각각 condition 조건을 주어서 해결하였습니다. 
liquorCtr의 증가시키는 부분에서 NPE가 뜨길래 putIfAbsent를 put으로 대체하였습니다
(아직도 의문.. putIfAbsent 함수에서 absent를 체크하는 조건을 어떻게 체크하는지 궁금하네여)

<br>

## 🎸 기타

closes #185

2023-09-13 04:10 UTC, whatasame requested changes
고생하셨습니다. 이번 PR과 관련된 내용은 아니지만 다음 사항도 고려해주세요

`LiquorQueryDslRepository`에서 `getList()`를 이용하기 위하여 `LiquorSearchCondition`를 반드시 사용해야하는데요. 이로 인해 `getCachedList()`에서 `LiquorSearchCondition.nullObject()`를 쓰고 있다.

이렇게 nullObject()를 쓰는 것보다 `getList()`에서 `LiquorSearchCondition`을 매개변수로 받지 않는 메서드를 오버로드해서 사용하는 것이 더 좋을 것 같아요. 

한 번 생각해보시고 코멘트 남겨주세요!

2023-09-13 04:10 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
Java Collection API의 HashMap을 기준으로 `Map.putIfAbsent(key, value)`는 기존 값이 있을 때 이전 값을 반환하고 없을땐 null을 반환합니다. 

이전 코드에서 `putIfAbsent()`의 반환값을 사용하진 않는데 어디서 NPE가 발생하나요? 테스트 코드가 있으면 좋겠어요.

2023-09-13 04:10 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +    @Cacheable(value = "liquorBrew", key = "#type", condition = "#type!=null", unless = "#result==null")
`Cacheable`과 속성 값에 관련된 정리된 자료가 있으면 공유 해주세요~

2023-09-13 04:10 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/config/CaffeineCacheConfig.java
> +import com.woowacamp.soolsool.global.infra.CacheType;
👍

2023-09-13 06:33 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +    @Cacheable(value = "liquorBrew", key = "#type", condition = "#type!=null", unless = "#result==null")
넹 여기 있습니다. https://succinct-gymnast-a8b.notion.site/882e279f3d1642ccb5b5491bda8b609a

2023-09-13 06:36 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
<img width="1280" alt="스크린샷 2023-09-12 오후 5 39 42" src="https://github.com/woowatechcamp/soolsool/assets/87687210/f7eaa85a-6dee-4894-9d10-6a3f507b8226">

정확히 말하자면 putIfAbsent가 아니라 liquorCtr.get(liquorId) 가 하는 부분에서 null 이 뜨는데 이 부분에서 replace 하는 과정에서 NPE가 뜹니다. 그래서 제 추측으로는 ifAbsent부분에서 absent의 조건이 무엇인지 모르겠지만 잘 처리가 되지 않는거 같아요.

2023-09-13 06:39 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
프론트로 실행시켜보면 사용한지, 즉시 increase할때는 오류가 안뜨지만, 1분 이상 경과후에 npe 가 뜨는 것으로 보아 ttl 관련 만료 문제 일거같아요 제 추측으로는

2023-09-13 06:47 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
그리고 어제 증가율에 대해서 의문점을 가졌었는데, 
1. initLiquorCtrIfAbsent -> get -> replace 로직에서 init할때는 ttl이 만료가 안되지만 get-> replace 과정에서 만료가 된다면 어떻게 될까?
2. 조회하는 부분에서 클릭률을 증가시키는 로직이 필요할까? 이는 프론트 측면에서 호출하는 거로 빼야한다 -> 즉 광고 도메인을 생성하여 API 로 빼야 한다. 
3. 현재 redis에서 클릭률을 계속 갱신해가며 5분마다 이를 업데이트 해주는 로직인데, 이럴 경우 5분 후에 클릭률이 변하지 않아도 만료가 되면 update 치는 일이 발생한다. -> 극단적으로 모든 물품을 조회하게 되면 redis에 모든 물품이 쌓이고 이는 5분마다 변하지 않아도 계속 만료가 된다. ->  캐쉬에 쌓이고 메모리 터짐 -> 레디스에 클릭률을 갱신하는 거보다, 레디스를 비우고 새롭게 조회시, 클릭률을 증가시키는 로직으로 해야 한다. 
4. redis가 만료될 때 이벤트를 발행하는 책임이 너무 크다.  스케줄러가 5분마다 배치를 돌려서 레디스 정보를 디비에 반영하고, 5분마다 레디스를 비워주는 것은 어떨까 
라는 생각을 하였습니다.

2023-09-13 06:49 UTC, worldii commented
> 위하여



> 고생하셨습니다. 이번 PR과 관련된 내용은 아니지만 다음 사항도 고려해주세요
> 
> `LiquorQueryDslRepository`에서 `getList()`를 이용하기 위하여 `LiquorSearchCondition`를 반드시 사용해야하는데요. 이로 인해 `getCachedList()`에서 `LiquorSearchCondition.nullObject()`를 쓰고 있다.
> 
> 이렇게 nullObject()를 쓰는 것보다 `getList()`에서 `LiquorSearchCondition`을 매개변수로 받지 않는 메서드를 오버로드해서 사용하는 것이 더 좋을 것 같아요.
> 
> 한 번 생각해보시고 코멘트 남겨주세요!

이부분에 대해서는 다시 생각해보고 리팩토링하겠습니다.

2023-09-13 20:04 UTC, worldii commented
해당 사항 수정했어요!!!!!!!

2023-09-14 03:11 UTC, whatasame approved these changes, later dismissed
고슴둥!

2023-09-14 03:11 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +        return getList(pageable, null);
```suggestion

        return getList(null, pageable, null);
```

아래 메서드 추가 없이 이것만 사용해도 될 것 같아요!

2023-09-14 03:11 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
음 여기서 다루기 아쉬운데, [Discussion](http://github.com/woowatechcamp/soolsool/discussions)에 올려서 다 같이 의논해봐요!

2023-09-14 05:16 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +        return getList(pageable, null);
그렇게 하면 condition.get 하는 부분에서 npe가 터질거 같아요!

2023-09-14 05:18 UTC, worldii commented
> 음 여기서 다루기 아쉬운데, [Discussion](https://github.com/woowatechcamp/soolsool/discussions)에 올려서 다 같이 의논해봐요!
이거 빼도 상관없어요.. 그거 해결할때까지 그냥 따로 계속 붙이면서 다닐게요 그럼

2023-09-14 14:36 UTC, worldii commented
appprove 부탁드립니다!

2023-09-14 18:35 UTC, whatasame requested changes
코멘트 확인 부탁드립니다! 아래는 궁금한 점입니다.

* Repository가 Service에서 사용하는 DTO를 반환하고 있는 것 같은데 Entity를 반환하는게 적절한 것 같아요. 어떻게 생각하시나요?

아래는 이전 코멘트에 대한 답변입니다.

> 이거 빼도 상관없어요.. 그거 해결할때까지 그냥 따로 계속 붙이면서 다닐게요 그럼

NPE 코드가 아닌 말씀해주신 4가지 의문점에 대한 이야기를 나눠보자는 의견이었습니다. 어떻게 생각하세요?

2023-09-14 18:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +        return getList(pageable, null);
맞네요... 대신 다른 방법이 생각나 다른 곳에 comment 달았습니다.

2023-09-14 18:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +    }
```suggestion
    private List<LiquorElementResponse> getFirstPageList(
        final Pageable pageable
    ) {
        return queryFactory.select(
                Projections.constructor(
                    LiquorElementResponse.class,
                    liquor
                )
            )
            .from(liquor)
            .orderBy(liquor.id.desc())
            .limit(pageable.getPageSize())
            .fetch();
    }
```

1. where절이 항상 null이어서 관련된 매개변수를 제거해봤습니다.
2. 좀 더 직관적으로 이름을 바꿔봤습니다. public 메서드와 private 메서드의 이름을 같게하는게 거슬렸는데 어떻게 생각하시나요?
3. 첫 페이지 쿼리를 QueryDsl이 아니라 Jpa를 이용하면 더 가독성이 좋을 것 같은데 어떻게 생각하세요?

2023-09-15 11:14 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +    }
1. 좋네요
2. 좋아요
3. 저는 동일한 조회역할을 하는 부분이 jpa, querydsl에 있으면 더 헷갈릴거같다고 생각이 드는데 어떻게 생각하시나요??

2023-09-15 11:32 UTC, worldii commented
> Repository가 Service에서 사용하는 DTO를 반환하고 있는 것 같은데 Entity를 반환하는게 적절한 것 같아요. 어떻게 생각하시나요?

> 위와 이어지는 이야기로 PageResponse의 of 메서드의 인자를 List<LiquorElementResponse>가 아닌 List<Liquor>로 받는게 좋을 것 같아요. 다른 DTO들은 DTO.from(Entity) 패턴으로 DTO를 생성했는데 외부에서 DTO를 만들어 넘기다보니 DTO.from(DTO)처럼 느껴지네요. order.dto.response의 DTO들을 참고해주세요.

네 해당 사항 바꾸었습니다!

2023-09-15 11:36 UTC, worldii commented
현재 조회가 아닌 클릭률 업데이트 로직이 조회 부분에 있어 Cacheable 적용이 QueryDsl Repository에 가있습니다.. 
조회가 아닌 클릭률 update도 같이 하고 있어서 책임이 크다고 생각하는데 이를 리팩터링 하면좋겠습니다 !!

2023-09-16 08:12 UTC, whatasame approved these changes
고생하셨습니다. 이만 approve 하도록 하겠습니다. 코멘트 하나 확인 해주세요.

2023-09-16 08:12 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
>      }
`PageLiquorResponse`에 있어야할 메서드 같아요. 정적 팩토리 메서드를 이용하면 팩토리 메서드에 이름도 붙일 수 있어서 좋을 것 같은데 어떻게 생각하세요? 

지금까지 DTO class에 Entity를 DTO에 넘겨서 DTO를 생성하는 패턴을 사용했는데 여기서는 Service에서 DTO를 생성하고 있네요.

2023-09-16 08:52 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
>      }
관련 피드백 반영하도록 하겠습니다!

2023-09-16 08:52 UTC, merged