feature: 첫 페이지 캐싱을 redis 로 변경
woowatechcamp/soolsool pull request #214
Opened 2023-09-12 19:39 UTC by worldii

## ♻️ 변경 사항

- [x] 여러 종류를 쓰기 위해 MultipleCacheManagerConfig 정의 
- [x] 카테고리, 첫 페이지 각각 cacheManager 명시 (기본 cacheManager는 redis로 설정)
<br>

## 📌 참고 사항

```
ex)
* 결제 부분 로직이 복잡한데, ~~~ 이유로 ~~~ 를 구현하기 위해 불가피했읍니다.
* ...
```

<br>

## 🎸 기타
closes #211

2023-09-13 04:19 UTC, whatasame requested changes
다음 사항을 고려해주세요.

1. 다른 PR의 브랜치와 구분되지 않아서 해당 PR에서 무엇이 변경되었는지 한 눈에 들어오지 않습니다. 브랜치를 구분해주세요.

2. 이미 Redisson을 이용해서 Redis를 사용하고 있는데 이번 PR은 기존 인프라를 사용하지 않고 별도의 redis starter의 `RedisTemplate`를 사용하는 것처럼 보이네요. Redisson과 RedisTemplate 둘 다 사용하는 건 관리 포인트만 늘어난다고 생각합니다. Redisson을 사용하는건 어떤가요?

3. 카테고리 캐싱도 Redis로 옮기는건 어떨까요? 카페인 캐시를 카테고리에서만 사용하고 있는데 Redis로 옮기는 게 관리 요소가 적어질 것 같아요.

4. 현재는 테스트를 통과하기 위해 로컬에서 Redis를 설치해야하는게 맞나요? 이 부분은 #205 에서 개선하려고 합니다.

2023-09-13 04:19 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +@NoArgsConstructor
바꾼 이유가 있을까요? 커밋 내역에서 왜 이렇게 바꿔야하는 지 찾지 못했어요 🥲

2023-09-13 06:51 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +@NoArgsConstructor
redis로 바꾸니까 조회과정에서 또 parse 과정에서 no creator 오류가 떴습니다. 해결방법을 찾을 수 없어 final을 빼고, noArgument를 추가하였는데, 혹시 이 오류 final을 붙이고도 해결가능할까요?

2023-09-13 07:16 UTC, worldii commented
> 



> 다음 사항을 고려해주세요.
> 
> 1. 다른 PR의 브랜치와 구분되지 않아서 해당 PR에서 무엇이 변경되었는지 한 눈에 들어오지 않습니다. 브랜치를 구분해주세요.
-> 네 이부분은 저도 인지를 했는데 어제 작업했던 클릭률 개선한 오류를 쓰고 싶어서 브랜치를 잘 못나눴습니다 죄송합니다 흑ㅎㄱ흑흐그
> 2. 이미 Redisson을 이용해서 Redis를 사용하고 있는데 이번 PR은 기존 인프라를 사용하지 않고 별도의 redis starter의 `RedisTemplate`를 사용하는 것처럼 보이네요. Redisson과 RedisTemplate 둘 다 사용하는 건 관리 포인트만 늘어난다고 생각합니다. Redisson을 사용하는건 어떤가요?
-> cache 추상화로 redistemplate 을 직접적으로 안쓰더라고요 그래서 redisTeplate을 삭제하였습니다. !!!!  
> 3. 카테고리 캐싱도 Redis로 옮기는건 어떨까요? 카페인 캐시를 카테고리에서만 사용하고 있는데 Redis로 옮기는 게 관리 요소가 적어질 것 같아요.
-> 카테고리는 제 생각에는 글로벌 캐쉬보다 로컬 캐쉬가 네트워크 처리속도면, 변경되지않는 부분, 그리고 차지하는 메모리도 적어 이대로 납둬도 괜찮다고 생각하는데 redis로 옮겨야 하는이유가 무엇일까요? 
> 4. 현재는 테스트를 통과하기 위해 로컬에서 Redis를 설치해야하는게 맞나요? 이 부분은 [test: Redis 테스트 환경을 Testcontainers 기반으로 변경 #205](https://github.com/woowatechcamp/soolsool/issues/205) 에서 개선하려고 합니다.
-> 네맞습니다. 현재 redis를 로컬에서 사용하고 있는데test container 방식으로 변경할 수 있다면 좋은 거 같습니다!

2023-09-13 07:28 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +@NoArgsConstructor
음... 이번 기회에 한 번 해결해보는 건 어떨까요? 

제가 정리한 자료도 공유해드릴게요

https://github.com/whatasame/TIL/commit/420a407dd8c7c564043f6cd7d7cb8463345b3672

https://github.com/whatasame/TIL/commit/5f1d9dbc7de429aee7d4d5bf27fc9cf4d1018aa5

2023-09-13 09:23 UTC, whatasame commented
> 카테고리는 제 생각에는 글로벌 캐쉬보다 로컬 캐쉬가 네트워크 처리속도면, 변경되지않는 부분, 그리고 차지하는 메모리도 적어 이대로 납둬도 괜찮다고 생각하는데 redis로 옮겨야 하는이유가 무엇일까요?

캐시 관리 포인트를 Redis 하나로 집중할 수 있을 것 같아서 이야기 해봤습니다!

2023-09-13 20:07 UTC, worldii commented
카테고리 캐싱 지우는거는 현재 변경사항 다 머지 되고 진행할게요!! 테스트 카테고리 조회하는거 다 깨질거같아서요

2023-09-14 03:55 UTC, whatasame requested changes
일단은 한 번 코멘트 더 남겨봤습니다...

2023-09-14 03:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
https://github.com/woowatechcamp/soolsool/pull/220#discussion_r1325315663

2023-09-14 03:55 UTC, whatasame commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
redisson을 사용중인데, start-data-redis를 사용하는 이유가 있나요?

2023-09-14 03:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +    @Cacheable(value = "liquorBrew", key = "#type", condition = "#type!=null", unless = "#result==null", cacheManager = "caffeineCacheManager")
이전에 링크해주신 `@Cacheable` 자료가 권한이 없다고 떠서 못 봤네요 ㅠ

2023-09-14 03:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/config/MultipleCacheManagerConfig.java
> +    }
이 Bean은 어디서 사용하나요?

2023-09-14 03:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/infra/RedisCacheType.java
> +}
```suggestion
@Getter
@RequiredArgsConstructor
public enum RedisCacheType {

    LIQUOR_FIRST_PAGE ("liquorsFirstPage", 60L),
    ;
    
    private final String cacheName;
    private final Long expireSeconds;
}
```

2023-09-14 03:55 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/config/CacheTestConfig.java
`MultipleCacheManagerConfig`와 동일한 것 같은데 중복해서 작성하는 이유가 있나요?

2023-09-14 03:55 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/config/CachingConfigurerSupport.java
`CachingConfigurerSupport `와 동일한 것 같은데 중복해서 작성하는 이유가 있나요?

2023-09-14 03:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/config/CachingConfigurerSupport.java
> +    }
```suggestion
public class CachingConfigurerSupport implements CachingConfigurer {

    @Override
    public CacheManager cacheManager() {
        return CachingConfigurer.super.cacheManager();
    }
```

2023-09-14 03:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/infra/CaffeineCacheType.java
> +public enum CaffeineCacheType {
구체적인 클래스 이름 좋아요~

2023-09-14 05:19 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +    @Cacheable(value = "liquorBrew", key = "#type", condition = "#type!=null", unless = "#result==null", cacheManager = "caffeineCacheManager")
어제 파일 옮기다가 그렇게 된거 같네요 팀 프젝 내에서 각자 한거 정리해서 올려도 좋을거같아요

2023-09-14 05:19 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +    @Cacheable(value = "liquorBrew", key = "#type", condition = "#type!=null", unless = "#result==null", cacheManager = "caffeineCacheManager")
이거도 커서기반이랑 같이 올려드릴게요 어차피 캐쉬 삭제 하면 다 없어질거같지만

2023-09-14 05:22 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/global/config/MultipleCacheManagerConfig.java
> +    }
여러 개(레디스, 카페인)의 캐쉬 추상화를 쓰게되면 어떤 캐쉬 매니저를 써야하는지 몰라 불명확하다는 에러가 떠요. 따라서 기본 캐쉬 매니저를 일단 레디스로 해줬어요

2023-09-14 05:25 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/config/CacheTestConfig.java
테스트용 컨피그를 따로 제작하는게 좋지 않을까요?

2023-09-14 05:26 UTC, worldii commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
redisson에 대한 이해도가 부족한데 , data-redis를 포함하는 관계인건가요?

2023-09-14 05:31 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/config/CachingConfigurerSupport.java
이거는빼겠습니다 근데 어차피 레디스만 쓰면 여기 제가 했던게 다 사라지긴합니다.

2023-09-14 14:21 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorBrewCache.java
> +    @Cacheable(value = "liquorBrew", key = "#type", condition = "#type!=null", unless = "#result==null", cacheManager = "caffeineCacheManager")
https://www.notion.so/09-13-By-a2c02eefb4664275988363d1643f5fab?pvs=4
여기다 넣어놨습니다!

2023-09-14 14:32 UTC, worldii commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
찾아보니 redisson은 Java에서 Redis를 더 쉽게 연동하고 사용할 수 있도록 제공하는 거 같고, data-redis는 스프링에서  Redis 데이터베이스와 상호 작용하기 위한 기능과 추상화를 제공하는 건데, 추상화를 쓰지 않고 자바에서 제공하는 라이브러리를 사용할 이유는 없어보이네요!

2023-09-15 09:55 UTC, whatasame requested changes
코멘트 확인 부탁드려요!

2023-09-15 09:55 UTC, whatasame commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
1. data-redis를 사용하자는 뜻으로 이해했는데 맞을까요?
2. 1번이 맞다면 그럼 기존의 Redisson을 data-redis로 통합해야하지 않나요?

2023-09-15 09:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/config/MultipleCacheManagerConfig.java
> +    }
왜 레디스를 기본 캐시 매니저로 설정하셨을까요? 선택의 이유에 대한 단순 궁금증입니다!

2023-09-15 09:55 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/config/CacheTestConfig.java
왜 좋은건가요?

2023-09-15 11:39 UTC, worldii commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
1. cache Manager 추상화는 data-redis에 있기 때문에 그렇게 하고 싶습니다! 
2. 통합이 가능한가요?  레디슨을 사용하는 방법이 저는 잘 몰라서.. 근데 찾아보니 redisson 라이브러리로 분산락을 많이 쓰던데 굳이 통합을 할 필요가 있을까요?

2023-09-15 11:40 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/global/config/MultipleCacheManagerConfig.java
> +    }
사용 용도가 저희 프로젝트에서 레디스가 더 범용적으로 많이 쓰인다고 생각해서 썼어요!

2023-09-15 11:53 UTC, worldii commented
반영하였습니다~

2023-09-15 11:53 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/config/CacheTestConfig.java
찾아보니 테스트 환경이 달라질때 구성하는게 맞네요!! 지금은 똑같아서 다 삭제했어요!

2023-09-15 12:34 UTC, whatasame commented
conversation 닫지 말아주세요~

2023-09-16 10:57 UTC, worldii commented
추후 카페인 캐쉬 다 걷어내도록할게여! CacheConfig하고

2023-09-17 08:39 UTC, worldii commented
머지하고 싶어!!!!!!!!!!!!!!!!!제발제ㅏㅂ레베자베랍제베자바렙자ㅔ밪

2023-09-17 12:11 UTC, hwihwi523 submitted a review, later dismissed
짱!

2023-09-17 12:11 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/PageLiquorResponse.java
> +        List<LiquorElementResponse> liquorElements = liquors.stream()
```suggestion
        final List<LiquorElementResponse> liquorElements = liquors.stream()
```

2023-09-17 12:11 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/global/config/MultipleCacheManagerConfig.java
> +        Map<String, RedisCacheConfiguration> cacheConfiguration = new HashMap<>();
```suggestion
        final RedisCacheConfiguration redisCacheConfiguration = RedisCacheConfiguration
            .defaultCacheConfig()
            .serializeKeysWith(RedisSerializationContext
                .SerializationPair
                .fromSerializer(new StringRedisSerializer()))
            .serializeValuesWith(RedisSerializationContext
                .SerializationPair
                .fromSerializer(new GenericJackson2JsonRedisSerializer()));

        final Map<String, RedisCacheConfiguration> cacheConfiguration = new HashMap<>();
```

2023-09-17 12:11 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/order/service/OrderServiceIntegrationTest.java
> +@DisplayName("통합 테스트:제 OrderService")
```suggestion
@DisplayName("통합 테스트: OrderService")
```

2023-09-17 12:11 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/PageLiquorResponse.java
> +        }
PageableExecutionUtils 쓰면 페이징 메타 데이터가 자동으로 구해지는 걸로 알고 있는데 카운트 쿼리 줄이려고 직접 하신 건가여???

2023-09-17 12:11 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +        return PageLiquorResponse.of(pageable, liquors);
98번째 줄에 final 빠졌읍니다.

2023-09-17 12:16 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/PageLiquorResponse.java
> +        List<LiquorElementResponse> liquorElements = liquors.stream()
짱입니다

2023-09-17 12:17 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/global/config/MultipleCacheManagerConfig.java
> +        Map<String, RedisCacheConfiguration> cacheConfiguration = new HashMap<>();
짱입니다

2023-09-17 12:17 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/core/order/service/OrderServiceIntegrationTest.java
> +@DisplayName("통합 테스트:제 OrderService")
짱입니다

2023-09-17 12:32 UTC, whatasame approved these changes
정말로 고생하셨습니다 😭

2023-09-17 15:14 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +        return PageLiquorResponse.of(pageable, liquors);
고치겠숩니다

2023-09-17 15:14 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/PageLiquorResponse.java
> +        }
넹!!!

2023-09-17 15:16 UTC, merged