refactor: LiquorCtr 반영 방식 리팩토링
woowatechcamp/soolsool pull request #219
Opened 2023-09-13 15:14 UTC by hwihwi523

## ♻️ 변경 사항

LiquorCtr 반영 방식 리팩토링

<br>

## 📌 참고 사항

### MySQL, Redis에 저장되는 CTR 정보
* Redis, MySQL 모두 전체 클릭수와 노출수를 저장하고 있고, 차이점은 아래와 같음
Redis : 최신 CTR 정보가 반영됨
MySQL : Redis로부터 flush 된 정보가 반영됨

### CTR 증가 흐름
1. 상품 목록 또는 상세정보 조회 시 Redis에 저장된 노출수 or 클릭수(이하 CTR)를 증가시킨다.
2. 만약 Redis에 저장된 CTR 정보가 없다면 아래의 명령을 수행한다.
    1. MySQL에서 CTR 정보를 조회한다.
    2. 조회한 CTR 정보를 Redis에 저장하고, 5분 후 만료되도록 설정한다.
3. 5분이 지나 데이터가 만료되면, Redis에 갱신된 CTR 정보를 MySQL에 반영한다.

### ea48b27 변동 사항
1. RedisLiquorCtr에 toEntity 추가 (-> LiquorCtr)
2. 클릭율 조회 시 toEntity를 통해 LiquorCtr로 변환한 후 getCtr 로직 재사용 (중복 로직 삭제)

=> toEntity를 추가하여 getCtr 중복 로직을 삭제하고, Entity가 Redis, Event 등 이곳저곳을 돌아다니는 문제 방지

<br>

## 🎸 기타

```
ex) 닫을 이슈가 있다면,
closes #이슈번호
```
closes #218

2023-09-15 07:23 UTC, worldii approved these changes, later dismissed
많이 배워갑ㅂ니다!!

2023-09-15 07:23 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtr.java
> +        this.click = new LiquorCtrClick(Objects.isNull(click) ? 0L : click);
각각 생성자 내에서 확인하는 건 어떨까요?

2023-09-15 07:23 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +                        event.getKey(),
순서가 궁금합니다
1. 해당 이벤트 발행
2. 이벤트 기록 디비 반영
3. redis 쌓여있는 LiquorCtr evict

2023-09-15 07:23 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        return liquorCtrs.get(liquorId);
만료가 되어도 이 전의 캐쉬를 참조하니 npe를 방지했다고 생각하면 될까요?

2023-09-15 07:54 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtr.java
> +        this.click = new LiquorCtrClick(Objects.isNull(click) ? 0L : click);
넵!! 부생성자 하나 만들어서 해당 생성자 이용하도록 수정했읍니다!

2023-09-15 07:55 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +                        event.getKey(),
1. 데이터 삽입 시 설정한 TTL 경과
2. Redis 데이터 만료(삭제) + 만료 이벤트 발생
3. 만료된 노출수 및 클릭수 데이터를 RDB에 반영

요 순서를 따릅니다!

2023-09-15 08:01 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        return liquorCtrs.get(liquorId);
정확히는 데이터가 만료되면 Redis에서 해당 데이터가 삭제되기 때문에 만료될 경우 이전의 캐시를 참조하지 않습니다!

그러나 결론적으로 Redis에서 데이터를 가져올 때 cache miss가 발생할 경우, RDB에서 데이터를 조회해 캐시를 새로 만들기 때문에 npe를 방지하는 게 맞긴 합니다!

2023-09-15 09:34 UTC, whatasame requested changes
어제 고민을 해봤는데 다음 항목에 대해 같이 의논해보면 좋을 것 같아요.

### RedisLiquorCtr의 필요성

`RedisLiquorCtr`에 노출수와 클릭수가 같이 저장되는데 이를 묶어서 객체를 저장할 필요가 있을까요? 노출수와 클릭수의 빈도를 봤을 때 아예 클릭이 되지 않는 상품도 존재할 텐데 노출 됐다고 클릭 수도 같이 캐시에 올리는건 낭비 같기도 했어요. 

현재는 Redis의 Key가 `LIQUOR_CTR`인데 이를 두 개로 나누어 `LIQUOR_CTR_CLICK`, `LIQUOR_CTR_IMPRESSION`으로 구분하고 Map의 타입을 <Long, Long>이나 <Long, LiquorImpression>, <Long, LiquorClick>으로 저장하는건 어떤가요?

이 경우 LiquorClick.getCtr(LiquorImpression)와 같이 비즈니스 로직을 다른 곳으로 옮길 수 있을 것 같아요.

결론부터 말하면 필요한 정보만 최소한으로 Redis에 올리는건 어떨까? 입니다!

2023-09-15 09:34 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtr.java
>      }
```suggestion
    @Builder
    public LiquorCtr(
        @NonNull final Long liquorId,
        final Long impression,
        final Long click
    ) {
        this.liquorId = liquorId;
        this.impression = new LiquorCtrImpression(impression);
        this.click = new LiquorCtrClick(click);
    }
```

가독성을 한 번 올려봤습니다!

2023-09-15 09:34 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtr.java
> +    @Getter
안 쓰이는 것 같아요

2023-09-15 09:34 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtr.java
음 빌더에서만 @NonNull이 먹히는 줄 알았는데 그냥 일반 생성자에서도 먹히는군요!

2023-09-15 09:34 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/event/listener/LiquorCtrExpiredEventListener.java
> +    @Async
`@Async` 가 없었더라면 이전에는 동기 이벤트였던건가요?

2023-09-15 09:34 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
Entity로 변경했으니 dirty check를 update 쿼리로 변경한다면 select 쿼리를 줄일 수 있을 것 같아요.

2023-09-15 09:34 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        return liquorCtrs.get(liquorId);
1. Redis에 올라온 데이터를 WAS 메모리에서 가져옴
2. 가져오자마자 Redis에서 해당 데이터가 만료
3. 만료된 데이터가 WAS에 돌아다님
4. 따라서 Redis에서 데이터가 만료되었지만 WAS 메모리에는 남아있으므로 NPE 방지

이런 느낌 맞나요?

2023-09-15 09:34 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
```suggestion
        final LiquorCtr liquorCtr = LiquorCtr.builder()
            .liquorId(1L)
            .impression(2L)
            .click(1L)
            .build();
```

뭔가 해당 given 절에서는 overwrite도 있어서 순수한 `getCtr()` 테스트가 아닌 것 같아요.

위처럼 변경하고 overwrite 테스트도 추가하면 어떨까요?

2023-09-15 09:34 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepositoryTest.java
>      }
코멘트가 잘 안달려서 불가피하게 이렇게 답니다..

```java
    @AfterEach
    void setUpLiquorCtr() {
        RMapCache<Long, RedisLiquorCtr> mapCache = redissonClient.getMapCache(LIQUOR_CTR_KEY);

        mapCache.clear();
    }
```

BeforeEach일 때 결국 Redis container에 LiquorCtr이 남아있을 것 같아서 AfterEach로 변경하는게 적절해보입니다.

테스트를 한 번 실행하면 Redis container가 하나 생성되고 모든 테스트에서 하나를 공유하더라구요. 만약에 다른 테스트에서 LiquorCtr을 사용하면 해당 테스트에서 생성한 LiquorCtr 값이 돌아다닐 것 같아요.

2023-09-15 09:34 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepositoryTest.java
> +    }
```suggestion
    @Test
    @Sql({"/liquor-type.sql", "/liquor.sql", "/liquor-ctr.sql"})
    @DisplayName("Redis에 Ctr 정보가 존재하지 않을 경우 DB를 조회해 Redis에 반영한다.")
    void synchronizeWithDatabase() {
        // given
        double expected = liquorCtrRepository.findByLiquorId(TARGET_LIQUOR)
            .orElseThrow(() -> new RuntimeException("LiquorCtr이 존재하지 않습니다."))
            .getCtr();

        // when
        double ctr = liquorCtrRedisRepository.getCtr(TARGET_LIQUOR);

        // then
        assertThat(ctr).isEqualTo(expected);
    }
```

중복된 테스트 같은데 맞나요?

2023-09-15 09:34 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepositoryTest.java
>      RedissonClient redissonClient;
다른 의존성을 가져와서 같이 테스트하는건 이들의 변경으로 테스트가 실패할 수도 있을 것 같은데. 어떻게 생각하세요?

2023-09-15 09:34 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/service/LiquorServiceIntegrationTest.java
`liquorCtrRedisRepository`, `redissonClient`와 같은 의존성을 혹시 제거할 수 있을까요? `LiquorService` 통합 테스트인데 다른 의존성이 테스트에 포함되어 있는게 테스트 의존성을 만들어 낼 것 같습니다.

일단 제가 지울 수 있는 것들은 지웠는데, 이상하다면 편하게 revert 해주셔도 됩니다!

2023-09-15 09:50 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/event/listener/LiquorCtrExpiredEventListener.java
> +    @Async
녜 지난 번에 오류가 팡팡 떠서 일단 동기로 실행했었는데, 비동기와는 관련이 없었던 오류라 다시 붙였읍니다!

2023-09-15 09:51 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
liquorId만 알고 있을 뿐 LiquorCtr의 pk는 알 수가 없어서 find가 불가피하다 생각했읍니다!

2023-09-15 11:21 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
첫 번째 코멘트 답변:
1. Redis 데이터가 만료됨 + 만료 이벤트 발생
2. 만료 이벤트를 통해 만료된 데이터가 WAS 적재됨
3. WAS 상에서 지연 쓰기 관련 만료 로직 처리 (RDB에 반영하는 로직)

요 세 단계는 이벤트 관련 로직이구요

코멘트 남겨주신 코드는 그냥 redis에 적재되어 있던 데이터를 가져오는 코드입니다!

두 번째 코멘트 답변:
크게 놓치고 있었는데 감사함다!!!!

2023-09-15 11:24 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepositoryTest.java
> +    }
아 맞네요!! getClick, getImpression 메서드가 사라지면서 하나로 통일됐는데 놓치고 있었습니다!! 감삼다!!!

2023-09-15 11:28 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepositoryTest.java
>      RedissonClient redissonClient;
/liquor-ctr.sql을 보고 expected를 직접 파악해야 하고, 게다가 통합 테스트여서 괜찮다 생각을 했었습니다!

우선 다른 테스트와 마찬가지로, 직접 조회해서 expected를 만드는 부분을 빼고 sql 파일에 있는 값을 기준으로 바로 검증하도록 수정했읍니다!

2023-09-15 11:40 UTC, hwihwi523 commented
> 어제 고민을 해봤는데 다음 항목에 대해 같이 의논해보면 좋을 것 같아요.
> 
> ### RedisLiquorCtr의 필요성
> `RedisLiquorCtr`에 노출수와 클릭수가 같이 저장되는데 이를 묶어서 객체를 저장할 필요가 있을까요? 노출수와 클릭수의 빈도를 봤을 때 아예 클릭이 되지 않는 상품도 존재할 텐데 노출 됐다고 클릭 수도 같이 캐시에 올리는건 낭비 같기도 했어요.
> 
> 현재는 Redis의 Key가 `LIQUOR_CTR`인데 이를 두 개로 나누어 `LIQUOR_CTR_CLICK`, `LIQUOR_CTR_IMPRESSION`으로 구분하고 Map의 타입을 <Long, Long>이나 <Long, LiquorImpression>, <Long, LiquorClick>으로 저장하는건 어떤가요?
> 
> 이 경우 LiquorClick.getCtr(LiquorImpression)와 같이 비즈니스 로직을 다른 곳으로 옮길 수 있을 것 같아요.
> 
> 결론부터 말하면 필요한 정보만 최소한으로 Redis에 올리는건 어떨까? 입니다!

오늘 한가로이 머리를 감으며 같은 생각을 해보았읍니다!
머리가 띵해서 `이거다!` 싶었는데요.. 다른 우려할 점이 생겨 버렸습니다..

제가 생각했던 우려할 점은 RDB에 저장된 CTR 정보가 오염될 수 있다는 것이었습니다!
왜냐하면 클릭수와 노출수가 각각 다른 시점에 RDB에 반영이 될 경우, 4분 전에 반영된 노출수와 1분 전에 반영된 클릭수를 기반으로 클릭율을 구하게 될 수도 있습니다.

물론, Redis에는 최신 클릭수와 노출수가 저장이 되어 있기도 하고, 현재의 클릭율 조회 기능은 Redis를 기반으로 계산하여 제공하고 있기 때문에 우려할 점은 발생하지 않습니다.

다만 Redis가 죽었을 경우 RDB로부터 CTR 정보를 가져 와 클릭율을 제공하는 로직도 추가해야 하는데, 이때 우려했던 문제가 발생할 수 있다고 생각하여 셀프 기각을 때리게 되었읍니다.

혹시 제가 말씀드린 요 부분들은 어떻게 생각하시나여??

2023-09-15 11:47 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/service/LiquorServiceIntegrationTest.java
음.. 수없이 짱구를 굴려 보았는데요..

가장 큰 문제점은 상세정보를 조회하는 것과 클릭수를 증가시키는 행위가 붙어 있다는 것이었습니다.

상세정보를 조회했을 때 클릭수가 정상적으로 증가하는지 확인을 해야 하는데, 확인하기 위해선 liquorCtrRepository로 직접 조회하거나, liquorCtrService의 메서드를 호출해서 확인할 수 있습니다. 그런데 이렇게 될 경우 저 둘 중 하나의 의존성은 가져야 해서.. 현재 마땅한 게 떠오르질 않네요..

---

redissonClient도 마찬가지로, Redis와 관련된 로직이 들어있어서 메서드 사이마다 데이터를 비워야 한다는 문제점이 있습니다..

2023-09-15 11:54 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtr.java
> +        this.click = new LiquorCtrClick(Objects.isNull(click) ? 0L : click);
오 짱

2023-09-15 12:30 UTC, whatasame requested changes
### 코멘트 답변

> 제가 생각했던 우려할 점은 RDB에 저장된 CTR 정보가 오염될 수 있다는 것이었습니다!
왜냐하면 클릭수와 노출수가 각각 다른 시점에 RDB에 반영이 될 경우, 4분 전에 반영된 노출수와 1분 전에 반영된 클릭수를 기반으로 클릭율을 구하게 될 수도 있습니다.

그럼 이벤트 로직에 클릭수와 노출수 중 하나가 flush 되면 같이 flush하는건 어떤가요? 이때 batch sql을 사용해서 하나의 쿼리로 처리할 수 있을 것 같아요.

update 쿼리와 새로 언급한 로직을 합친 방법의 특징은 다음과 같네요.
* 장점: Redis에 적재되는 데이터의 양을 줄일 수 있다. `RedisLiquorCtr`을 쓰지 않고 기존의 `LiquorCtrClick`, `LiquorCtrImpression`을 쓸 수 있다.
* 단점: 둘 중 하나가 5분이 지나지 않았음에도 flush 된다. (batch sql로 하면 문제 없을 것 같습니다.)

### 의견

LiquorCtrRedisRepository의 메서드 모두를 LiquorCtrService로 옮겨도 될 것 같은데 어떻게 생각하세요? 그랬을 때 LiquorCtrService가 다음과 같은 의존성을 갖는건 자연스럽게 느껴지네요.

* LiquorCtrRepository
* RedissonClient

2023-09-15 12:30 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
`liquor_id`가 FK이고 1:1 관계라서 가능하지 않을까요?

2023-09-15 12:30 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/service/LiquorServiceIntegrationTest.java
두 문제 모두 https://github.com/woowatechcamp/soolsool/issues/201 를 해결하면 될 것 같은데 어떤가요?

2023-09-15 12:30 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
> 요 세 단계는 이벤트 관련 로직이구요
> 코멘트 남겨주신 코드는 그냥 redis에 적재되어 있던 데이터를 가져오는 코드입니다!

그럼 LiquorCtr 단위 테스트에서 만료 이벤트를 고려하고 있는건가요?

2023-09-15 12:30 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepositoryTest.java
>      RedissonClient redissonClient;
> 우선 다른 테스트와 마찬가지로, 직접 조회해서 expected를 만드는 부분을 빼고 sql 파일에 있는 값을 기준으로 바로 검증하도록 수정했읍니다!

`liquorCtrRepository`을 뺐다는 말씀이신가요?

2023-09-15 13:31 UTC, hwihwi523 commented
> ### 코멘트 답변
> > 제가 생각했던 우려할 점은 RDB에 저장된 CTR 정보가 오염될 수 있다는 것이었습니다!
> > 왜냐하면 클릭수와 노출수가 각각 다른 시점에 RDB에 반영이 될 경우, 4분 전에 반영된 노출수와 1분 전에 반영된 클릭수를 기반으로 클릭율을 구하게 될 수도 있습니다.
> 
> 그럼 이벤트 로직에 클릭수와 노출수 중 하나가 flush 되면 같이 flush하는건 어떤가요? 이때 batch sql을 사용해서 하나의 쿼리로 처리할 수 있을 것 같아요.
> 
> update 쿼리와 새로 언급한 로직을 합친 방법의 특징은 다음과 같네요.
> 
> * 장점: Redis에 적재되는 데이터의 양을 줄일 수 있다. `RedisLiquorCtr`을 쓰지 않고 기존의 `LiquorCtrClick`, `LiquorCtrImpression`을 쓸 수 있다.
> * 단점: 둘 중 하나가 5분이 지나지 않았음에도 flush 된다. (batch sql로 하면 문제 없을 것 같습니다.)
> 
> ### 의견
> LiquorCtrRedisRepository의 메서드 모두를 LiquorCtrService로 옮겨도 될 것 같은데 어떻게 생각하세요? 그랬을 때 LiquorCtrService가 다음과 같은 의존성을 갖는건 자연스럽게 느껴지네요.
> 
> * LiquorCtrRepository
> * RedissonClient

혹시 RedisLiquorCtr을 빼려 하시는 이유가 무엇일까여??
저는 여전히 JPA 엔티티가 레디스에 저장되는 게 조금 걸리는데다가 DTO로서 사용하는 건 괜찮다 생각을 하거든여
그리고 일단 getCtr에 대한 중복 로직도 제거가 된 상태구요,,,

2023-09-15 13:37 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepositoryTest.java
>      RedissonClient redissonClient;
넵 뺀 상태입니다!

2023-09-15 13:38 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
요 더티 체킹에 관한 건 아무래도 그때 얘기 나눴던 게 또 문제가 될 것 같습니다!
만약 상품이 삭제되어 LiquorCtr도 같이 삭제된 상태에서 LiquorCtr 지연 쓰기 이벤트가 실행되면 그땐 update 쿼리가 아니라 insert 쿼리가 나가는 문제입니다!

2023-09-15 13:38 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/service/LiquorServiceIntegrationTest.java
해결될 것이라 생각하지만 일단 현재 PR에서 해결할 건 아니라 생각합니다..!

2023-09-15 13:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
아 1 ~ 4번 내용 코멘트가 월디가 아니라 와타사메 코멘트였군여!

계속 생각해 봤지만 사실 저는 NPE에 관련된 이야기를 잘 이해하지 못하겠어요..!

캐시(Redis)를 조회하려 했을 때,
1. miss -> RDB로부터 조회하여 캐시를 새로 등록한 뒤 해당 데이터를 반환한다.
2. hit -> 기존에 저장되어 있던 데이터를 반환한다.

lookUpLiquorCtr 메서드는 이러한 로직입니다!

> 1. Redis에 올라온 데이터를 WAS 메모리에서 가져옴
> 2. 가져오자마자 Redis에서 해당 데이터가 만료
> 3. 만료된 데이터가 WAS에 돌아다님
> 4. 따라서 Redis에서 데이터가 만료되었지만 WAS 메모리에는 남아있으므로 NPE 방지

일단 Redis에서 데이터를 가져오자마자 데이터가 만료되는 게 아닙니다.
정해진 TTL이 지나 해당 데이터가 만료(삭제)되면, Redis 만료 이벤트가 발생합니다.
이후 Redis 만료 이벤트 리스너가 해당 이벤트를 감지하여 WAS에서 지연 쓰기를 하는 이벤트를 발생시킵니다.
지연 쓰기가 완료되면 Redis에서 만료된 데이터는 남지 않고 그냥 사라집니다.

무엇보다 코멘트를 달아주신 코드를 보면 해당 코드는 그냥 캐시를 조회하는 메서드입니다. 단지 hit, miss 여부에 따라서 RDB에서 조회해올지 말지 등 처리가 달라지는 것뿐이에요.

2023-09-15 14:37 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
> liquor_id가 FK이고 1:1 관계라서 가능하지 않을까요?

한 가지 더 생각이 났는데요!

현재 상품 등록 로직이
`Liquor 저장 -> LiquorCtr 저장`
요 순서대로 이루어지고 있는데, 이 두 작업이 항상 atomic하게 처리된다는 보장은 없을 것 같습니다!

만약 Liquor 저장이 1, 2번 쓰레드 순서로 이루어졌을 때, LiquorCtr을 저장하는 것마저 같은 순서를 보장할 순 없을 것 같아요!

2023-09-16 09:00 UTC, whatasame requested changes
코멘트 확인해주세요~

2023-09-16 09:00 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/service/LiquorServiceIntegrationTest.java
넵 혹시 시간나시면 진행해주실 수 있을까요?

2023-09-16 09:00 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
> 일단 Redis에서 데이터를 가져오자마자 데이터가 만료되는 게 아닙니다.

만료됐다는 상황을 가정한거였습니다! 하하 역시 소통은 어렵군요...

> 지연 쓰기가 완료되면 Redis에서 만료된 데이터는 남지 않고 그냥 사라집니다.

넵 근데 Redis에서 메모리로 가져온 데이터는 참조를 들고 있으면 언제든 재사용할 수 있는거 아닌가요? Redis에서 만료된 데이터가 WAS에서 계속 참조 하고 있으면 돌아다닌다는 것을 말하고 싶었습니다.

> 무엇보다 코멘트를 달아주신 코드를 보면 해당 코드는 그냥 캐시를 조회하는 메서드입니다. 

> 첫 번째 코멘트 답변:
> Redis 데이터가 만료됨 + 만료 이벤트 발생
> 만료 이벤트를 통해 만료된 데이터가 WAS 적재됨
> WAS 상에서 지연 쓰기 관련 만료 로직 처리 (RDB에 반영하는 로직)
> 요 세 단계는 이벤트 관련 로직이구요
> 코멘트 남겨주신 코드는 그냥 redis에 적재되어 있던 데이터를 가져오는 코드입니다!

`LiquorCtrTest`는 도메인 단위 테스트인데 Redis를 고려하는게 이상하다는 점에서 시작한 코멘트였습니다. 아무리 생각해도 `LiquorCtr`은 POJO인데 Redis를 고려해야할 필요가 있나 싶어서요...

2023-09-16 09:00 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
### 지연 쓰기 시 insert

> 요 더티 체킹에 관한 건 아무래도 그때 얘기 나눴던 게 또 문제가 될 것 같습니다! 만약 상품이 삭제되어 LiquorCtr도 같이 삭제된 상태에서 LiquorCtr 지연 쓰기 이벤트가 실행되면 그땐 update 쿼리가 아니라 insert 쿼리가 나가는 문제입니다!

"이미 사라진 LiquorCtr에 update 쿼리를 날리면 사라진 LiquorCtr이 다시 살아난다"고 이해했는데요. 맞나요? 우선 제가 이해한 대로 쿼리를 실행하면 다시 살아나지 않습니다.

![image](https://github.com/woowatechcamp/soolsool/assets/97666463/06079c14-76b1-477b-8b04-8a6fa3dc5259)

### 동시성 문제

> 만약 Liquor 저장이 1, 2번 쓰레드 순서로 이루어졌을 때, LiquorCtr을 저장하는 것마저 같은 순서를 보장할 순 없을 것 같아요!

저장 순서가 뒤바뀌는 예를 한 번 들어보겠습니다.

1. T1: liquor 저장 => liquor.id = 1;
2. T2: liquor 저장 => liquor.id = 2;
3. T2: liquor_ctr 저장 => liquor_ctr.id = 1, liquor_ctr.liquor_id=2;
4. T1: liquor_ctr 저장 => liquor_ctr.id = 2, liquor_ctr.liquor_id=1;

이 상황에서 업데이트하는 상황은 다음과 같습니다.

1. Redis miss
2. RDB에서 id = 2인 liquor_ctr을 읽어온다.
3. Redis에 LIQUOR_CTR-2로 저장
4. Redis에 지연 쓰기
5. 5분뒤 만료 이벤트 발행
6. 이벤트에서 id = 2인 liquor_ctr의 liquor_id = 1 획득
7. 업데이트 쿼리 실행

`update liquor_ctr set click = 777 where liquor_id = 1`

다른 상품의 Ctr을 바꿀 순 없을 것 같은데 어떤 경우를 말하시는 걸까요?

### 의문점

현재 Redis에 LiquorCtr을 저장할 때 "LIQUOR_CTR-2"이면 liquor_id = 2인 liquor_ctr을 저장한다. 맞나요? 갑자기 겁나 헷갈리네요. 순간 id = 2인 LiquorCtr이 저장된 줄 알았어요.

2023-09-16 10:01 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
> 1. Redis miss
> 2. RDB에서 id = 2인 liquor_ctr을 읽어온다.
> 3. Redis에 LIQUOR_CTR-2로 저장
> 4. Redis에 지연 쓰기
> 5. 5분뒤 만료 이벤트 발행
> 6. 이벤트에서 id = 2인 liquor_ctr의 liquor_id = 1 획득
> 7. 업데이트 쿼리 실행

liquorId로 저장하기 때문에 LIQUOR_CTR-1에 1번 상품의 CTR 정보가 저장됩니다.

그리고 무엇보다 더티체킹은 영속성 컨텍스트 안에 있어야 가능한데 만료 이벤트가 발생할 때까지 컨텍스트 안에 남아 있다는 보장을 할 수 있을까요?

저는 보장을 할 수 없다고 생각해서 해당 엔티티를 save 해서 반영해야 한다고 생각했습니다.

그런데 save를 했을 때, 이미 존재하는 데이터는 정상적으로 변경되겠지만, 혹여나 만료 이벤트가 발생하기 전에 상품 삭제 API가 호출된다면 update 쿼리가 아니라 insert 쿼리가 나갑니다. 물론 Liquor도 삭제됐기 때문에 제약조건으로 인해 LiquorCtr이 생성되진 않겠지만, 적어도 방지할 수 있는 오류는 어플리케이션 단에서 방지하는 게 좋다고 생각합니다.

따라서 앞서 말씀드린 이유들 때문에 실제로 데이터를 반영하기 전에 조회할 필요성이 있다고 생각합니다.

2023-09-16 10:07 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
> 넵 근데 Redis에서 메모리로 가져온 데이터는 참조를 들고 있으면 언제든 재사용할 수 있는거 아닌가요? Redis에서 만료된 데이터가 WAS에서 계속 참조 하고 있으면 돌아다닌다는 것을 말하고 싶었습니다.

당연히 그러겠지만 요청이 끝난 후에도 어떻게 참조한 값을 계속 유지할 수 있는지 이해가 잘 되지 않네여..

> LiquorCtrTest는 도메인 단위 테스트인데 Redis를 고려하는게 이상하다는 점에서 시작한 코멘트였습니다. 아무리 생각해도 LiquorCtr은 POJO인데 Redis를 고려해야할 필요가 있나 싶어서요...

LiquorCtrTest, LiquorCtrRepositoryTest 모두 Redis를 고려하지 않고 있는데 혹시 어느 부분 말씀하신 건가여??

2023-09-16 10:07 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/service/LiquorServiceIntegrationTest.java
넵!!!!! 당근빳다죠!!

2023-09-16 10:23 UTC, whatasame requested changes

2023-09-16 10:23 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/service/LiquorServiceIntegrationTest.java
assignee에 할당해놓을게요!

2023-09-16 10:23 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
## comment 1
> 당연히 그러겠지만 요청이 끝난 후에도 어떻게 참조한 값을 계속 유지할 수 있는지 이해가 잘 되지 않네여..

맞습니다. 억지로 상황을 만들어 봤습니다! 크게 신경은 안쓰셔도 될 것 같아요.

## comment 2

> LiquorCtrTest, LiquorCtrRepositoryTest 모두 Redis를 고려하지 않고 있는데 혹시 어느 부분 말씀하신 건가여??

최초에 코멘트를 단 이유는 클릭률을 구하는 곳에서 `overwrite()`를 호출해서 왜 호출했는지 물어본 것이었습니다. 그냥 LiquorCtr을 가져오거나, 생성해서 바로 구하면 되기 때문이죠.

제가 했던 질문은 다음과 같습니다.

> 뭔가 해당 given 절에서는 overwrite도 있어서 순수한 getCtr() 테스트가 아닌 것 같아요.

이때 다음과 같이 답변해주셨습니다.

> 첫 번째 코멘트 답변:
> 
> Redis 데이터가 만료됨 + 만료 이벤트 발생
> 만료 이벤트를 통해 만료된 데이터가 WAS 적재됨
> WAS 상에서 지연 쓰기 관련 만료 로직 처리 (RDB에 반영하는 로직)
> 요 세 단계는 이벤트 관련 로직이구요
> 
> 코멘트 남겨주신 코드는 그냥 redis에 적재되어 있던 데이터를 가져오는 코드입니다!

`overwrite()` 코드에 대해 물어봤는데 이벤트와 Redis에 적재되어있던 데이터라고 말씀해주셔서 순수한 도메인 테스트에서 Redis를 고려하고 있는건 아닐까? 하는 질문이었습니다.

다시 돌아와서,  클릭률을 구하는 `getCtr()`을 테스트하는 코드에 `overwrite()`를 작성하신 이유가 궁금합니다.

2023-09-16 10:23 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
> liquorId로 저장하기 때문에 LIQUOR_CTR-1에 1번 상품의 CTR 정보가 저장됩니다.

실수... 했습니다 ㅠ LIQUOR_CTR-1 맞습니다!

2023-09-16 10:23 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
클릭수와 노출수를 더티 체킹으로 업데이트 해야하는 이유가 있을까요? 

최종 데모 데이 때 조언 받았던 update 한 번으로 해결하는 방법을 적용하자는 뜻이었습니다.

2023-09-16 11:29 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
> 클릭수와 노출수를 더티 체킹으로 업데이트 해야하는 이유가 있을까요?
> 
> 최종 데모 데이 때 조언 받았던 update 한 번으로 해결하는 방법을 적용하자는 뜻이었습니다.

update += 네이티브 쿼리가 아닌 JPA로 업데이트 하려는 이유가 Redis에는 증가량을 저장하고 있지 않기 때문이었습니다!

Redis에는 항상 최신 클릭수와 노출수를 저장하고 있고, 시간이 지나 RDB에 최신 데이터를 덮어 씌우는 형태다 보니 update += 쿼리를 사용하려면 다른 연산이 필요하더라구요!

아래에서 경우의수를 좀 나누어 보았읍니다!!

1. Redis에 노출수와 클릭수의 증가량을 저장할 경우.
    클릭율 조회 : (RDB 클릭수 + Redis 클릭수) / (RDB 노출수 + Redis 클릭수)

    1. update += 쿼리 사용 시,
        update CTR += Redis CTR

    2. JPA 사용 시,
        RDB CTR 조회
        조회한 엔티티에 Redis CTR을 더하기
        더티체킹

2. Redis에 최신 노출수와 클릭수를 저장할 경우,
    클릭율 조회 : Redis 클릭수 / Redis 노출수

    1. update += 쿼리 사용 시,
        RDB CTR 조회
        조회한 엔티티에 (Redis CTR - RDB CTR)을 더하기 -> (어플리케이션 단에서 직접 조회하고 증가량을 연산하기 때문에 동시성 문제가 발생할 수 있습니다!)
        더티체킹

    2. JPA 사용 시,
        RDB CTR 조회
        Redis CTR로 덮어 쓰기
        더티체킹

이렇게 나눌 수가 있는데요!

여기서 우리 상황에 맞게 요약해 보자면,
데모 데이 때 받았던 피드백은 직접 락을 걸지 않고 update += 쿼리를 이용하는 것으로 동시성을 제어하기 충분하다는 것이었습니다!

그러나 현재 Redis에 최신 CTR을 저장하고 있기 때문에 += 쿼리를 이용하려면 증가량을 직접 계산해야 하며, 그에 따라 동시성 문제가 발생할 수 있다고 생각했습니다.
따라서 최신 CTR을 저장하고 있는 현 상황에선 동시성 제어를 직접 해야 하는 만큼 추가 로직이 없는 JPA 엔티티로 데이터를 갱신해야겠다고 판단했습니다!!
(*추가 로직 : 조회한 엔티티에 (Redis CTR - RDB CTR)을 더하기)

2023-09-16 11:33 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
> 최초에 코멘트를 단 이유는 클릭률을 구하는 곳에서 overwrite()를 호출해서 왜 호출했는지 물어본 것이었습니다. 그냥 LiquorCtr을 가져오거나, 생성해서 바로 구하면 되기 때문이죠.

앗 현재 코드는 바로 아래의 피드백이 반영되어 있는 상태입니다!

> 뭔가 해당 given 절에서는 overwrite도 있어서 순수한 getCtr() 테스트가 아닌 것 같아요.

> 위처럼 변경하고 overwrite 테스트도 추가하면 어떨까요?

이 피드백을 받기 전까지 제가 크게 놓치고 있어서..ㅠㅠㅠㅠㅠ
그래서 getCtr()에서 overwrite() 메서드 호출부를 제거했고, overwrite() 테스트도 추가한 상태입니다!!

2023-09-16 17:04 UTC, jjungsk submitted a review, later dismissed
덕분에 많이 배웠습니다 :)
개인적으로 EventHandler, 지연 쓰기, 분산 락 관련하여 학습 후 직접 코드를 작성하며 학습을 한 뒤에 더 꼼꼼한 코드 리뷰가 가능할 것 같숩니다. 😆

2023-09-16 17:04 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/SoolsoolApplication.java
> +@EnableAsync
에이씽크 조하요

2023-09-16 17:04 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorDetailResponse.java
> +    private final List<LiquorElementResponse> relatedLiquors; // TODO: 연관 상품 API 분리
연관 상품 API 분리 좋은것 같숩니다^^

2023-09-16 17:04 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/event/listener/LiquorCtrExpiredEventListener.java
> +        liquorCtrService.writeBackCtr(event.getLiquorCtr());
@EventListener 에 대해 학습하니 보통 다른 domain 에 있는 Service에 event를 발생시키는 것으로 알고 있는데
호오옥시 return 값도 받을 수 있을 까요??
예를 들어 
final int liquorId = liquorCtrService.writeBackCtr(event.getLiquorCtr()); 일 때 이벤트를 발생시키는 곳이
LiquorCtrService 가 아닌 LiquorService에서 해당 이벤트의 결과 값을 받을 수 있는 고런 너낌??

2023-09-16 17:04 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/event/listener/LiquorCtrExpiredEventListener.java
> +        liquorCtrService.writeBackCtr(event.getLiquorCtr());
자문자답이긴 한데 AxonFramework 라이브러리를 추가해 EventBus (Store 너낌)에 발행된 event의 결과값을 저장하는 context가 있다고 합니다.
MSA가 유행 하면서 spring boot 에 친화적인 AxsonFramework + AxonSever 에 대한 인지도가 높아지고 DDD 설계 및 CQRS (제가 간단히 이해 하기로는 Command (cud 삽입, 업데이트, 삭제) & Query(read 조회) 를 비동기적으로 분리하여 처리하는 방식) 패턴을 구현하기 위한 프레임 워크라고 합니다.
호기심이 생겨 자세히 학습하고 추가 공유하도록 하겠숩니다^^

https://docs.axoniq.io/reference-guide/axon-framework/events/event-bus-and-event-store

2023-09-16 17:24 UTC, whatasame reviewed
아마 다음 리뷰에는 approve 될 것 같은 느낌적인 느낌

2023-09-16 17:24 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtrTest.java
> +        liquorCtr.overwrite(new LiquorCtr(1L, 2L, 1L));
아하! ㅇㅅㅇ(역시 소통은 어렵다)

2023-09-16 17:24 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
> Redis에는 항상 최신 클릭수와 노출수를 저장하고 있고, 시간이 지나 RDB에 최신 데이터를 덮어 씌우는 형태다 보니 update += 쿼리를 사용하려면 다른 연산이 필요하더라구요!

현재 로직이 다음과 같지 않나요? id = 1인 LiquorCtr을 `LIQUOR_CTR-1`로 표현하겠습니다.
1. WAS 실행
2. `LIQUOR_CTR-1`의 click 1 증가 요청
3. `LIQUOR_CTR-1`를 Redis에서 조회
4. Redis miss
5. `LIQUOR_CTR-1`를 MySQL에서 가져옴 ( click = 50이라고 가정 )
6. Redis에 저장
7. Redis의 `LIQUOR_CTR-1` 값을 1 증가( click = 51 )
8. `LIQUOR_CTR-1` 만료

이때, 말씀하신대로 증가량이 아닌 최신 클릭수를 저장하고 있기 때문에 update += 가 아닌 다음 쿼리를 실행하면 될 것 같아요.

```sql
UPDATE liquor_ctrs SET click = 51 WHERE id = 1;
```

즉, += 쿼리가 아닌 = 쿼리를 사용하자는 것입니다!

2023-09-16 19:13 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
현재도 +=이 아니라 = 쿼리를 쓰고 있습니다!!

그래서 조금 생각을 해봤는데요! 혹시 그럼 앞에서 말씀하셨던 update 쿼리가 데모 데이 때 받았던 동시성을 제어하기 위한 += update가 아니라, 조회 쿼리를 줄이기 위한 네이티브 쿼리 = update를 말씀하신 건가여????

2023-09-16 19:13 UTC, hwihwi523 commented
> 아마 다음 리뷰에는 approve 될 것 같은 느낌적인 느낌

오열 😭😭😭😭😭

2023-09-16 19:15 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/event/listener/LiquorCtrExpiredEventListener.java
> +        liquorCtrService.writeBackCtr(event.getLiquorCtr());
> @eventlistener 에 대해 학습하니 보통 다른 domain 에 있는 Service에 event를 발생시키는 것으로 알고 있는데
> 호오옥시 return 값도 받을 수 있을 까요??

이벤트 처리 결과를 반환해서 다른 곳에서 쓸 수 있냐는 말씀이신 거죠????

만약 그렇다면...! 조금 더 알아봐야 하겠으나 이미 답변을 바로 주셨군여.. 잘 참고하겠읍니다!!

2023-09-17 06:17 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
넵 네이티브 쿼리입니다! 

> 동시성을 제어하기 위한 += update

이게 무슨 말인지 이해하지 못했습니다. = update, += update 모두 배타락이 걸려서 동시성 문제가 발생하지 않는거 아닌가요?

2023-09-17 06:59 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorCtrService.java
>  }
> 데모 데이 때 받았던 피드백은 직접 락을 걸지 않고 update += 쿼리를 이용하는 것으로 동시성을 제어하기 충분하다는 것이었습니다!

기존 반영 방식은 어플리케이션 단에서 기존 CTR을 조회한 뒤, 1을 더한 후 update 하는 방식이었습니다.
그런데 CTR 조회 시점에서 동시성 문제가 발생할 수 있으니 원자적으로 처리하기 위해 락을 직접 걸어주었던 것이구요!

그래서 데모 데이 때 update += 피드백을 받았습니다.
update += 쿼리를 사용하면 어플리케이션이 아니라 DB에서 직접 조회와 반영을 원자적으로 처리하니 개발자가 락을 따로 걸어주지 않아도 됐기 때문입니다.

현재 상황은 만료 시간 5분의 텀도 있고, 최신 정보로 덮어 씌우는 것이다 보니 동시성 문제는 없을 것이라 예상을 합니다.
다만 피드백을 받았던 이유가 락에 관한 문제였기 때문에, 계속 데모 데이 update를 언급하신 이유가 동시성 문제를 다르게 처리하자는 말씀인 줄 착각했습니다!

일단 기존 쿼리는 네이티브 쿼리로 수정했으니 확인 부탁드립니다~

2023-09-17 07:14 UTC, whatasame approved these changes
죠습니다...

2023-09-17 07:33 UTC, merged