refactor: 커서 방식 부분에 정렬 기준 클릭률 순 추가
woowatechcamp/soolsool pull request #220
Opened 2023-09-13 18:02 UTC by worldii

## ♻️ 변경 사항

저 이거는 넣고 싶어요.. 오늘 하루종일한거기도 하고..
그때 판매량이나 클릭률 조인해서 하고 싶었는데 너무 시간이 없어서 못했던 거여서......
커서기반 할때 pk 방식만 있는데 커서기반 왜 했냐고 했잖아여..,
그 답변에 대해서 클릭률 넣어서 커버링 인덱스 걸면 정렬하는데 용이하다고 말할 수도 있다고 생각해서요...
기능 빼라고 하셨지만,, 클릭률 조인 몇줄 추가한게 다라서 넣게해주세여..ㅠㅠ

<br>
@jjungsk 세권오빠 그 오빠 필드에서 day가 예약어라고해서 조회를 하려니까 안되더라고,,, 그래서 이름을 다 statistic 을 붙여서 바꿨어! 

<br>

## 🎸 기타
closes #210

2023-09-14 03:41 UTC, whatasame requested changes
고생하셨습니다. 그런데 어떤 것을 어떻게 바꿨는지 PR 본문에서 명확하게 알 수가 없네요.

무엇을 왜, 어떻게 변경했는지 나열 형식으로 PR 본문을 수정해주시면 리뷰에 도움이 될 것 같아요. 클릭률 정렬을 어떻게 구현했는지, dto는 왜 바꿨는지 등등 전체적인 변경사항을 나열해주시면 좋을 것 같아요.

이러한 내용이 없어서 커밋 히스토리를 살펴봤는데 커밋 단위가 너무 크고, 커밋 제목이 추상적이거나 본문이 존재하지 않아 커밋의 의미가 퇴색된 것 같아요.

2023-09-14 03:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorCtrClick.java
> +    private Long click;
이거 왜 바꾼건가요? 이번에도 커밋 단위가 너무 크네요...

2023-09-14 03:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
음... 해당 dto는 상품 간단 정보 출력인데 왜 click count가 있나요...? 

상품 조회를 할 때 상품 클릭수도 같이 조회하나요? 그렇다면 `LiquorCtrController`의 책임을 `LiquorController`에서 같이 담당하는 것 같아요.

2023-09-14 03:41 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/service/StatisticsServiceTest.java
> +class StatisticsServiceTest {
DisplayName이 필요해요!

2023-09-14 03:41 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/service/StatisticsServiceTest.java
> +    }
given when then 양식을 지켜주세요.

2023-09-14 03:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/auth/config/AuthWebConfig.java
> +            .excludePathPatterns("/api/metrics", "/api/actuator/**");
...? 바로 위에 있는 `/api/pay/success`는 api를 안붙이는데 얘는 왜 붙이는건가요?

커밋 본문에 왜 그런건지 아무것도 없네요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2023-09-14 03:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsId.java
> +    @Column(name = "statistic_day")
지금까지 day로 했을 때 잘 되던거 아닌가요? 예약어라서 문제가 발생했다지만 이전에는 왜 day로 동작했을까요?

지금은 우리끼리 프로젝트를 하는거지만 실제 운영중인 서비스라고 생각했을 때, 테이블의 컬럼을 바꾸는 대공사를 해야합니다. 그럴 때 statistics의 row가 다수 있다고 하면 컬럼을 바꾸는 것만으로도 서비스가 중단될 수 있다고 하더라구요.

2023-09-14 03:41 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/service/StatisticsServiceTest.java
> +    void getStatisticsTest() {
```suggestion
    void findAll() {
```

2023-09-14 03:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
1. QueryDsl에서 지원하는 함수 eq를 감싼 함수는 equalsRegion()과 같이 메서드명을 좀 더 친절하게 작성하면 이해가 쉬울 것 같아요.

2. cursorId()라는 메서드가 무엇을 하는건지 잘 나타나지 않아요.

3. cursorId가 liquors의 id와 대응되는 값인가요?

4. 클릭수를 기준으로 페이징을 하는데 liquor id가 필요한가요?

2023-09-14 03:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +            .orderBy(liquor.id.desc(), liquorCtr.click.click.desc())
liquorCtr.click.click을 제가 만들긴 했지만 정말 골때리네요.

위에서 clickCount라는 좋은 표현을 사용하셨던데 LiquorCtrClick의 내부 필드명을 click에서 count로 변경해도 좋을 것 같아요.

2023-09-14 03:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
이 변경사항이 없으면 테스트에 실패하나요? 현재 다른 PR에서 Redis 관련 리팩터링을 하고 있어서 나중에 conflict 날 가능성이 높네요.

2023-09-14 05:01 UTC, worldii commented
커밋 단위를 이야기해서 말씀드리는 건데 처음 커밋 단위를 어차피 합쳐지니 막 해도 된다고 한건 오빠가아니었나요...? 허허허

2023-09-14 05:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/LiquorCtr.java
> +    @Embedded
이부분은 jpql 에서도 컨버터로 가져오는 부분이 없더라고요,,, 진짜 못찾겠어서 자문을 구하러 4조팀한테도 물어봤는데 거기도 컨버터 결국 그래서 뺏다고해서,, 이거만 임베디드로 바꿨어여ㅜㅜ

2023-09-14 05:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorCtrClick.java
> +    private Long click;
컨버터 연장선으로 붙여줬습니다

2023-09-14 05:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
클릭률 순으로 정렬 하려면 당연히 가져와야 하는 부분입니당..  그렇다고 dto를 따로 만들자니 너무 많은 변경사항을 가져가기 싫어서 추가했어요 liquor 와liquorCtr를 조인했기 때문에 책임을 명백히 나눌 수없다고 생각합니다.

2023-09-14 05:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/global/auth/config/AuthWebConfig.java
> +            .excludePathPatterns("/api/metrics", "/api/actuator/**");
이거 잘못들어갔어요.. 근데 api붙이는 순간부터 프로메테우스 집에서 저도 이해도 높일라고 해보려니까 안되서 추가해본거에요..

2023-09-14 05:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsId.java
> +    @Column(name = "statistic_day")
처음에 클릭률을 조회하는 걸 전체 통계 테이블에서 했었는데, 그때 jpa 단순 조회 테스트에서 오류가 났고, 정상적으로 작동하는 건 네이티브 쿼리로 짜서 update를 하는 것만 있어서 가능했다고 생각합니다.

2023-09-14 05:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
1. 글쎄요 이건 사람마다 차이인거 같은데 저는 eq가 queryDsl에서 지원하는 만큼 더 직관적이라고 생각했는데요
2.  커서 기반을 찾아보시면 알거 같네요.. 전 이정도면 직관적이라고 생각합니다. 
3. 불리안 expression을 보셨을까요?
4. 네 필요합니다.

2023-09-14 05:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
프론트에서 해당 테스트를 시험할때 자꾸 500이 뜹니다. 저도 건드리고 싶지 않았는데 자꾸 다른 에러로 프론트가 막가서 시험을못해보는게 짜증났어요

2023-09-14 07:19 UTC, whatasame requested changes
> 커밋 단위를 이야기해서 말씀드리는 건데 처음 커밋 단위를 어차피 합쳐지니 막 해도 된다고 한건 오빠가아니었나요...? 허허허

맞습니다! 근데 PR 수정 내역이 명확하지 않아서 커밋을 보려다 힌트를 얻기 어려워서 한 말이었습니다. 둘 중 한 곳에서는 명확한 정보가 있으면 리뷰할 때 도움이 될 것 같아요.

QueryDsl과 관련해서 제가 모르는게 많아서 드린 리뷰가 많은데 잘 답변해주셔서 감사합니다 👍

2023-09-14 07:19 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
> 1. 글쎄요 이건 사람마다 차이인거 같은데 저는 eq가 queryDsl에서 지원하는 만큼 더 직관적이라고 생각했는데요

넵 취향 리뷰였습니다 ㅠ

> 2. 커서 기반을 찾아보시면 알거 같네요.. 전 이정도면 직관적이라고 생각합니다.
> 3. 불리안 expression을 보셨을까요?

`cursorId()`의 매개변수가 cursorId인게 헷갈려서 질문드렸습니다! 혹시 변수 cursorId가 liquorId가 아닌 이유가 있을까요?

> 4. 클릭수를 기준으로 페이징을 하는데 liquor id가 필요한가요?

제가 한 번 테스트를 해봤는데 아래의 statement 둘 다 동일한 쿼리가 나가는 것 같습니다.

1. 현재
```java
return
    liquorCtr.click.click.lt(click)
        .or(liquorCtr.click.click.eq(click).and(liquor.id.lt(cursorId)));
```

```
Hibernate: 
    select
        liquor0_.id as col_0_0_,
        liquorctr1_.click as col_1_0_,
        liquor0_.id as id1_7_,
        liquor0_.created_at as created_2_7_,
        liquor0_.modified_at as modified3_7_,
        liquor0_.alcohol as alcohol4_7_,
        liquor0_.brand as brand5_7_,
        liquor0_.brew_id as brew_id11_7_,
        liquor0_.image_url as image_ur6_7_,
        liquor0_.name as name7_7_,
        liquor0_.price as price8_7_,
        liquor0_.region_id as region_12_7_,
        liquor0_.status_id as status_13_7_,
        liquor0_.total_stock as total_st9_7_,
        liquor0_.volume as volume10_7_ 
    from
        liquors liquor0_ 
    inner join
        liquor_ctrs liquorctr1_ 
            on (
                liquor0_.id=liquorctr1_.liquor_id
            ) cross 
    join
        liquor_status liquorstat2_ 
    where
        liquor0_.status_id=liquorstat2_.id 
        and liquor0_.region_id=? 
        and liquor0_.brew_id=? 
        and liquorstat2_.name=? 
        and liquor0_.brand=? 
        and liquor0_.id<? 
    order by
        liquor0_.id desc,
        liquorctr1_.click desc limit ?
  ```

2. 수정한 버전
```java
return liquorCtr.click.click.eq(click).and(liquor.id.lt(cursorId));
```

```
Hibernate: 
    select
        liquor0_.id as col_0_0_,
        liquorctr1_.click as col_1_0_,
        liquor0_.id as id1_7_,
        liquor0_.created_at as created_2_7_,
        liquor0_.modified_at as modified3_7_,
        liquor0_.alcohol as alcohol4_7_,
        liquor0_.brand as brand5_7_,
        liquor0_.brew_id as brew_id11_7_,
        liquor0_.image_url as image_ur6_7_,
        liquor0_.name as name7_7_,
        liquor0_.price as price8_7_,
        liquor0_.region_id as region_12_7_,
        liquor0_.status_id as status_13_7_,
        liquor0_.total_stock as total_st9_7_,
        liquor0_.volume as volume10_7_ 
    from
        liquors liquor0_ 
    inner join
        liquor_ctrs liquorctr1_ 
            on (
                liquor0_.id=liquorctr1_.liquor_id
            ) cross 
    join
        liquor_status liquorstat2_ 
    where
        liquor0_.status_id=liquorstat2_.id 
        and liquor0_.region_id=? 
        and liquor0_.brew_id=? 
        and liquorstat2_.name=? 
        and liquor0_.brand=? 
        and liquor0_.id<? 
    order by
        liquor0_.id desc,
        liquorctr1_.click desc limit ?
```

제가 잘못 테스트 한걸까요? 의도대로라면 `cursorId()`가 최종적으로 sql로 가면 어떤 statement가 되나요?

2023-09-14 07:19 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
1. 혹시 `clickCount`로 FE에서 정렬을 하나요?

2. 1번이 맞다면 QueryDsl로 가져온 List는 이미 클릭수로 내림차순 정렬이 된 것 아닌가요?

2023-09-14 07:19 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/auth/config/AuthWebConfig.java
> +            .excludePathPatterns("/api/metrics", "/api/actuator/**");
아하! 혹시 궁금한거 있으면 언제든 물어보세요

2023-09-14 07:19 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsId.java
> +    @Column(name = "statistic_day")
아하! 그럼 결국 잘 되던게 아니었군요. 착각했습니다... 🥲

2023-09-14 07:19 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/service/StatisticsServiceTest.java
> +    }
굳이 지울 필요는 없지만 편한대로 해주셔도 될 것 같습니다.

결국엔 @jjungsk 이 분께서 테스트 작성을 해주셔야할 것 같긴 하네요.

2023-09-14 13:06 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
그건 아닌데,  마지막 liquorCount를 가져오려면 필요한 부분입니다 ㅠㅠ

2023-09-14 13:07 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/service/StatisticsServiceTest.java
> +    }
지우고, 세권오빠한테 테스트 작성해달라고 할게용 ㅎㅎ

2023-09-14 13:07 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/global/auth/config/AuthWebConfig.java
> +            .excludePathPatterns("/api/metrics", "/api/actuator/**");
이것도 지우겠습니당 ㅎㅎ

2023-09-14 13:09 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
2번에 대해서는 제가 커서Id 메서드를 헷갈리게 네이밍한 부분이 잇는거 같네용 ㅠㅠ 죄송합니다 liquorId, clickCount로 고쳤어요!

2023-09-14 13:11 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
4. 

<img width="459" alt="스크린샷 2023-09-14 오후 9 44 43" src="https://github.com/woowatechcamp/soolsool/assets/87687210/617e831a-d995-4e2b-b8dd-bb16fa0c0674">

혹시 제 브랜치에서(feature/210-1)에서 실행해본 결과일까요? 저는 저렇게 뜨기는 합니다!

2023-09-14 13:11 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +            .orderBy(liquor.id.desc(), liquorCtr.click.click.desc())
넵 변경사항 고치겠습니다!!

2023-09-14 13:17 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
아 테스트를 저는 프론트에서 하고 있는데, 커서가 null일 경우의 조건(liquorId 가 null이거나, LiquorId가 null) 만을 타가지고 그럴 수도 있을거 같아요 !

2023-09-14 13:21 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
cross조인이 왜 되었을까요???

2023-09-15 10:00 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
테스트를 프론트에서 하는건 부적절해보입니다. TDD가 아닐 뿐더러 반복가능한 테스트가 어렵기 때문이에요. 실제로 제가 첨부한 쿼리 로그는 작성된 테스트 코드를 돌렸을 때 출력된 결과였어요. 테스트 코드를 작성해서 테스트 해주시길 바랍니다.

2023-09-15 10:09 UTC, whatasame requested changes
코멘트 확인 부탁드려요

2023-09-15 10:09 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
그럼 나중에 클릭수 정렬, 노출수 정렬, 판매수 정렬 등등 조건이 늘어날 때마다 필드가 늘어나나요?

2023-09-15 10:09 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
https://github.com/woowatechcamp/soolsool/pull/220/files/74447a1c80ba2c03886cbad3148ad87cf2304b38#r1327080247

참고해주세요

2023-09-15 10:09 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +            .getList(liquorSearchCondition, pageable, cursorId,clickCount);
```suggestion
            .getList(liquorSearchCondition, pageable, cursorId, clickCount);
```

2023-09-15 10:09 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/service/StatisticsServiceTest.java
> +    }
까먹지 않게 이슈 발행해주세요

2023-09-15 12:00 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
그떄는 새롭게 dto를 만들수 있을거 같습니다 다른 요청일 테니까요

2023-09-15 12:01 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/service/StatisticsServiceTest.java
> +    }
넵!

2023-09-15 12:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/redisson/LiquorCtrRedisRepository.java
> +        liquorCtr.put(
넹 !

2023-09-15 12:08 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(cursorId, clickCount)
넵 알겠습니당 cross 조인 확인해보니 전에 배포할때 안되는 오류때문에 잠시 고쳤던게 저렇게 들어갔네요 ㅠㅠ

2023-09-15 14:08 UTC, worldii commented
테스트 추가하였습니다!

2023-09-16 08:31 UTC, whatasame requested changes
코멘트 확인해주세요~

2023-09-16 08:31 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
곰곰히 생각해봤는데 최신순 검색이 사라지고 클릭순 + 최신순 기능으로 변경되었네요.

요구 사항의 변경이 없었는데 기존 기능을 삭제한 이유가 궁금합니다.

이 경우 새 상품이 추가되더라도 첫 페이지에는 항상 있던 상품만 보이게 될 것 같네요.

2023-09-16 08:31 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepositoryTest.java
> +                Pageable.ofSize(10), 1L, null
then 절을 보다 구체적으로 작성하는게 좋을 것 같습니다. `assert.isEmpty()`로는 클릭순 + 최신순이라는 기능을 검증하지 못할 것 같아요.

2023-09-16 08:31 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
>          );
기존에 단순 조회 역할을 하던 `LiquorElementResponse`가 클릭 정보를 포함하게 됨으로써 이를 의존하고 있던 `LiquorDetailResponse`에도 클릭 정보 0L이 포함되었습니다. 

커서에 필요한 클릭 정보가 상세 조회 DTO에 포함되면 안될 것 같아요. 따라서 `LiquorElementResponse`는 그대로 두고 클릭순 정보를 포함하는 DTO와 컨트롤러 메서드를 별도로 만들어할 것 같은데 어떻게 생각하시나요?

2023-09-16 09:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
네 맞아요. 삭제한거라기 보다, 클릭률을 도입하면서 최신순 검색이 아니라 인기순 검색으로 목록 조회를 바꿨다고 생각했습니다. 
물론 새로 클릭률 정렬을 따로 쿼리로 만들수도 있었는데, 그럼 프론트도 인기순 정렬, 최신 순 정렬이 생겨야 해서, 기존꺼에서 최소한의 변경으로 바꿔봤습니다.

2023-09-16 10:02 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepositoryTest.java
> +                Pageable.ofSize(10), 1L, null
클릭수가 널값일때 liquorId는 1이면, 마지막으로 읽은 liquorId가 1이기 때문에 그보다 작은게 없어 empty가 반환됩니다. 데이터를 더 넣어서 클릭수가 널값일 때 liquorId를 비교하는 걸 테스트 하라는 말씀이실 까요? 아 또한, (1, null) 가 같은 요청은 프론트에서 전해지지 않긴 합니다.

2023-09-16 10:03 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
>          );
음 사실 계속 그생각을 했었는데 더 생성하면 혼날거같아서 많이 안바꿔 볼라고 했었어요 그럼 dto 만들어서 진행하도록 하겠습니다.

2023-09-16 10:05 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepositoryTest.java
> +                Pageable.ofSize(10), 1L, null
처음 커서 (Null, null) -> 그다음 커서 (11,33) -> (10,33) -> (9,22) 과 같이 전달되고 데이터가 없을 경우엔 요청이 안되기 때문입니다.

2023-09-16 10:52 UTC, worldii commented
어우 동시에 다른 풀리퀘에 동일한 클래스를 작업하니까 헷갈리네요

2023-09-16 10:59 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
메서드 나누도록 하겠습니다!

2023-09-16 12:20 UTC, worldii commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepositoryTest.java
> +                Pageable.ofSize(10), 1L, null
아하 알았다 테스트 추가하도록할게요!

2023-09-16 16:33 UTC, jjungsk submitted a review, later dismissed
QueryDsl과 Cursor 방식에 대해 학습이 부족 했었는데 덕분에 찾아가며 공부 하면서 많이 배웠습니다 :) 소소한 코멘트 몇가지 남겼습니다! 시간 될때 한번 확인해 주세요 ☺️

2023-09-16 16:33 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        @RequestParam @Nullable final Long clickCount,
해당 부분 @RequestParam 값이 너무 많은것 같은데 @ModelAttribute 로 Dto로 맵핑하는건 어떻게 생각하시나요??

https://www.baeldung.com/spring-mvc-and-the-modelattribute-annotation

2023-09-16 16:33 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/LiquorElementResponse.java
> +    public static LiquorElementResponse of(final Liquor liquor) {
from ^^

2023-09-16 16:33 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +}
Dto 보다는 살짝 Domain 느낌도 드는것 같숩니다!
boolean hasNext;
Optional<Long> nextCursorId;
Optional<Long> nextClickCount;
List<LiquorClickElementResponse> liquor; // dto가 아닌 domain 으로..?
필드를 갖는 domain을 추가하여 로직을 수행하고 해당 dto에서는 domain -> toDto 등 변환만 하는 방법도 괜찮을것 같습니다
같이 생각해봐도 좋을것 같아요^^

2023-09-16 16:33 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/repository/StatisticsRepository.java
해당 부분에서 예약어 문제가 있었군요.. 꼼꼼하게 확인했어야 했는데 죄송합니다 😢

2023-09-17 07:41 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        @RequestParam @Nullable final Long clickCount,
좋은 것 같습니다^^

2023-09-17 07:42 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/LiquorElementResponse.java
> +    public static LiquorElementResponse of(final Liquor liquor) {
오 ^^

2023-09-17 07:46 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +}
List liquor; // dto가 아닌 domain 으로..? 이게 뭔말일까요??

2023-09-17 07:48 UTC, whatasame requested changes
다음 리뷰에서는 approve 될 것 같네요!

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
감사합니다! 참고로 BE 프로젝트이므로 FE는 고려하지 않는게 좋다고 생각합니다. 이유는 다음과 같습니다.

* BE의 변경 사항으로 인해 FE의 코드가 바뀌는 것은 당연하다. (역도 성립)
* FE의 변경 없이 기능 추가, 변경을 하다보면 FE의 코드에 의존하게 된다.
* FE에 의존하면 테스트 코드를 작성하지 않고 FE로 테스트하게 된다.

더 이상의 데모 데이는 없으니 잠시 내려두고 나중에 실제 EC2 연결 할 때 한 번에 수정하는건 어떤가요?

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/LiquorClickElementResponse.java
> +public class LiquorClickElementResponse {
`LiquorElementResponse` 상속을 고려해보셨나요?

* 장점: 코드 재활용
* 단점: 강하게 결합

변경하라는 것은 절대 아니고 이러한 상황에서 종하님의 의견이 궁금합니다! 지금도 좋다고 생각해요!

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        @RequestParam @Nullable final Long clickCount,
오 좋은데요?

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        final PageRequest sortPageable = getSortedPageable(pageable);
```suggestion
        final PageRequest sortPageable = PageRequest.createdAtDesc(pageable);
```

정적 팩터리 메서드에 이름을 붙여서 private 메서드와 매직 넘버를 다른 곳에서 관리할 수 있을 것 같은데 어떻게 생각하시나요?

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorStockController.java
> +import com.woowacamp.soolsool.core.liquor.dto.request.LiquorStockSaveRequest;
오 분류 조아요~

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/LiquorClickElementResponse.java
> +    }
안 쓰는 생성자 발견!

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/LiquorElementResponse.java
>      public LiquorElementResponse(final Liquor liquor) {
안 쓰는 생성자 발견!

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +}
```java
        if (liquors.size() < pageable.getPageSize()) {
            return new PageLiquorClickResponse(false, liquors);
        }
```

아마 이 부분 때문에 그러신 것 같은데, 저는 DTO로 느껴집니다!

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorResponse.java
> +    @JsonCreator
어떤 Response는 `@RequiredArgsConstructor`이고, 어떤건 `@JsonCreator`를 사용하네요.

제가 알기론 `@RequiredArgsConstructor`으로 충분한 걸로 아는데 이유가 있을까요?

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorResponse.java
> +            .map(LiquorElementResponse::of)
```suggestion
            .map(LiquorElementResponse::from)
```

of 메서드는 삭제해도 될 것 같아요!

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +        final List<LiquorClickElementResponse> liquors
```suggestion
        final List<Liquor> liquors
```

`PageLiquorResponse`처럼 Entity를 받으면 좋을 것 같아요.

2023-09-17 07:48 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(liquorId, null)
`cursorId(liquorId)`, `clickCursorId(liquorId, click)`으로 구분하면 안되겠죠...?

나중에 다른 필터링 조건이 들어왔을 때도 하나의 `cursorId()`를 사용한다면 최신순 조회 메서드도 영향을 받아 변경하기 때문에 OCP를 위반하는 것 같습니다.

2023-09-17 07:58 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/LiquorClickElementResponse.java
> +    }
음 이거는 queryDsl에서 프로젝션할 때 어쩔수없이 써야 합니다!

2023-09-17 07:58 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/LiquorElementResponse.java
>      public LiquorElementResponse(final Liquor liquor) {
이거도 QUERYDSL에서 매핑할때 써야합니다!

2023-09-17 07:59 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorResponse.java
> +            .map(LiquorElementResponse::of)
마자요 ...

2023-09-17 08:02 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/LiquorClickElementResponse.java
> +public class LiquorClickElementResponse {
굳이? 라는 생각이 드네요!! ㅋㅋㅋㅋㅋ 갠적으로 dto는 직관적으로 볼수 있으면 좋겠다고 생각이 들어서요!!

2023-09-17 08:05 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        final PageRequest sortPageable = getSortedPageable(pageable);
페이지 리퀘스트는 제가 정의한게 아닌데, 상속해서 새로운 객체 생성하여 메서드를 만들라는 말씀이실까요???

2023-09-17 08:08 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorResponse.java
> +    @JsonCreator
required 가  안될때 jsonCreator를 붙여서 해결했던 거 같아요 한번 다시 시도해보겠습니다

2023-09-17 08:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +        final List<LiquorClickElementResponse> liquors
그거는 어렵습니다.. 저도 바꾸어봤는데, 마지막 클릭수를 가져올라면은 querydsl에서 liquor가 아닌 liquorClick이 합쳐진 dto를 받아야합니다. 쇼핑몰 미션 때도 cartProduct와product를 같이 하실때는 일급컬렉션 같이 정의해서 map해주었지만, 진우님께서, dto를 사용하는건 어떻냐고 해서 그렇게 했던 경험이 있습니다. entity를 반환해야 하는이유를 잘 모르겠습니다.

2023-09-17 08:30 UTC, worldii reviewed
고쳤습니다!@@

2023-09-17 08:30 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
페이지 네이션 목록조회는 갠적으로 프론트 없이 테스트 하기가 어렵다고 생각합니다. 왜냐하면 백엔드가 내려준 데이터를 기반으로 상호 작용 방식으로 요청을 하게 되기 때문입니다.  
또한 백엔드의 데이터 형식 또한 프론트에서 어떻게 찍힐지 생각을 해서 구상할 수 있었습니다. 
다른 부분 같은 경우에는 프론트를 키지 않았지만, 결제 로직 실행 여부나 다음과 같은 페이지 네이션 목록 조회는 프론트에 의존적일 수 밖에 없다고 생각합니다.

2023-09-17 08:30 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepository.java
> +                cursorId(liquorId, null)
당장 지금은 할필요없다고 생각했습니다. 왜냐하면  현재의 클릭순 조회는 클릭순이 존재하지 않는다면 최신순이기 때문입니다. 따라서 메서드가 늘어날 때 나눠도 되지 않을 까라고 생각들었습니다.

2023-09-17 11:12 UTC, whatasame requested changes
코멘트 확인해주세요~

2023-09-17 11:12 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +        final List<LiquorClickElementResponse> liquors
지금 보니까 말씀하신 이유로 `LiquorQueryDslRepository.getListByClick()`가 Entity가 아닌 DTO를 반환하고 있네요. 하나의 DTO가 presentation layer, application layer, data layer 세 곳에서 사용하는데 괜찮은건가요?

2023-09-17 11:12 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorResponse.java
> +    @JsonCreator
생성자가 여러 개인 경우 명시적인 JsonCreator가 없다고 예외가 터질 수도 있긴 합니다! 그럴 땐 붙여야하구요.

2023-09-17 11:12 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/LiquorElementResponse.java
> +    private final Long clickCount;
인수 테스트로 가능하지 않을까요? 

결제 로직은 실제로 서버가 모르는 동작이 필요해서 불가능하지만 커서 테스트는 시나리오 테스트로 가능할 것 같습니다

2023-09-17 11:12 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        final PageRequest sortPageable = getSortedPageable(pageable);
```java
    private  PageRequest getSortedPageable(Pageable pageable) {
        return PageRequest.of(
            pageable.getPageNumber(),
            pageable.getPageSize(),
            Sort.by("createdAt").descending()
        );
    }
```

아뇨 바로 아래 부분에 있는 코드를 DTO 클래스로 이동하면 어떨까? 라는 생각이었습니다.

정적 팩토리 메서드 패턴의 장점인 생성자에 유의미한 이름을 붙일 수 있다를 of, from으로만 활용하는게 아쉬워서요!

2023-09-17 11:36 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +        final List<LiquorClickElementResponse> liquors
그럼dto를 새로 만드는게 날까요? 아니면 도메인을 하나 더 정의하는게 나을까요?

2023-09-17 12:04 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +        final List<LiquorClickElementResponse> liquors
별도의 비즈니스 로직이 없으니 Service-Repository 사이의 DTO가 적절할 것 같아요. 이런걸 해결하는 CQRS 패턴 같은게 있다고 하는데 자세히 공부는 안해봤어요

2023-09-17 12:04 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/repository/LiquorQueryDslRepositoryTest.java
> +                Pageable.ofSize(10), 1L, null
실제 샘플 데이터들을 추가해서 커서 뿐만 아니라 데이터까지 검증했으면 더 좋은 테스트 코드가 될 것 같아요. 선택 사항입니다!

2023-09-17 12:04 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/service/LiquorServiceIntegrationTest.java
> +            null, liquorId+1, null
```suggestion
            null, liquorId + 1, null
```
Code style을 팀에서 사용하는 파일을 사용하는지 점검해볼 필요가 있을 것 같아요.

2023-09-17 14:45 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/dto/response/PageLiquorClickResponse.java
> +        final List<LiquorClickElementResponse> liquors
dto 이용하면, 기존에 liquor ->liquorElementRespons를 바꾸어 주었는데 liquorClickElementResposne -> liquorElementResponse로 바꿀수있을거같아요

2023-09-18 14:37 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        final PageRequest sortPageable = getSortedPageable(pageable);
어떤 dto말씀하시는 걸까요?? PageRequest는 Pageable 에서 제공하는 클래스입니다!

2023-09-18 15:16 UTC, worldii commented
다했어 내가 100 채웠어 댓글 이제 그만 나를 나줘 
![image](https://github.com/woowatechcamp/soolsool/assets/87687210/e9613355-930f-4d46-96b2-e13c0131b72f)

2023-09-19 03:42 UTC, whatasame approved these changes, later dismissed
![image](https://github.com/woowatechcamp/soolsool/assets/97666463/536d285a-d682-47b1-940c-2e66bafef49c)

고생하셨습니다... 😭😭😭😭😭

2023-10-14 12:02 UTC, whatasame approved these changes
😊

2023-10-14 12:04 UTC, worldii commented
감사합니다

2023-10-14 12:04 UTC, merged