feat: 통계 top5 price, quantity 상품 조회 기능 추가
woowatechcamp/soolsool pull request #224
Opened 2023-09-16 08:02 UTC by jjungsk

## ♻️ 변경 사항

* top5 조회 by sale price 기능 추가
* top5 조회 by sale quantity 기능 추가
* 조회 결과 캐싱 기능 추가

<br>

## 🎸 기타

closes #207

2023-09-16 08:32 UTC, hwihwi523 requested changes
자잘한 것뿐입니다!!!

2023-09-16 08:32 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/SoolsoolApplication.java
>  }
편-안

2023-09-16 08:32 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    }
오 저는 매번 getMapCache 썼었는데 이렇게 바꿔 봐야겠네요

2023-09-16 08:32 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +        rCacheStatistics.put(STATISTICS_PRICE, statisticsLiquors);
```suggestion
        final StatisticsLiquors statisticsLiquors
    ) {
        rCacheStatistics.put(STATISTICS_PRICE, statisticsLiquors);
```

2023-09-16 08:32 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRepositoryImpl.java
> +        stopWatch.stop();
System.curmill~~~ 와 어떤 차이가 있나여???

2023-09-16 08:32 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRepositoryImpl.java
> +        LocalDate startDate = dateNow.minusDays(CTR_UPDATE_DURATION);
```suggestion
        final LocalDate startDate = dateNow.minusDays(CTR_UPDATE_DURATION);
```

2023-09-16 08:32 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRepositoryImpl.java
> +        LocalDate startDate = dateNow.minusDays(SALES_UPDATE_DURATION);
```suggestion
        final LocalDate startDate = dateNow.minusDays(SALES_UPDATE_DURATION);
```

2023-09-16 08:32 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/service/StatisticsService.java
> +        StatisticsLiquors statisticsLiquors = statisticsRepository.findTop5LiquorIdAndSalePrice();
```suggestion
        final StatisticsLiquors statisticsLiquors = statisticsRepository.findTop5LiquorIdAndSalePrice();
```

2023-09-16 08:32 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/service/StatisticsService.java
> +        StatisticsLiquors top5LiquorByQuantities = statisticsRepository.findTop5LiquorIdAndSaleQuantity();
```suggestion
        final StatisticsLiquors top5LiquorByQuantities = statisticsRepository.findTop5LiquorIdAndSaleQuantity();
```

2023-09-16 08:32 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquorsTest.java
> +@DisplayName("단위 테스트: StatisticsLiquors")
인수나 통합 테스트도 있나여???

2023-09-16 09:53 UTC, whatasame requested changes
고생하셨습니다. 인상깊은 코드가 많았습니다!!!

### 테스트 관련 

ATDD는 안하신건가요? 인수 테스트, 통합 테스트 등 구현된 기능에 비해 테스트가 너무 부족하네요. 

테스트 코드를 돌려봄으로써 어떤 기능을 구현한지 알 수 있는데, 없어서 아쉬웠습니다.

### 네이밍 관련

통계 Entity와 관련된 클래스들의 이름이 statistic**s**로 되어있는데, 현재 패턴으로는 패키지, 클래스는 단수로 작성하고 테이블 이름만 복수로 작성하고 있어요. 일관성을 위해 statistic으로 고쳐주시면 좋을 것 같아요.

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/controller/StatisticsController.java
> +            = statisticsService.findTop5LiquorsBySalePrice();
```suggestion
        final List<LiquorSalePriceResponse> liquorSalePriceResponses =
            statisticsService.findTop5LiquorsBySalePrice();
```

고치라는 건 아니지만 저는 이렇게 사용하긴 합니다! 신기하네요.

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquors.java
> +public class StatisticsLiquors {
일급 컬렉션에서 정말 사소한 부분까지 신경쓰신 게 느껴집니다...! 👍

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/dto/response/LiquorSalePriceResponse.java
> +    private Long totalSalePrice;
```suggestion
@Getter
@RequiredArgsConstructor
public class LiquorSalePriceResponse {

    private final Long id;
    private final String name;
    private final String brew;
    private final String region;
    private final String imageUrl;
    private final Long totalSalePrice;
```

지금까지 DTO 패턴과 일관성을 맞춰봤습니다!

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/dto/response/LiquorSalePriceResponse.java
> +    public static LiquorSalePriceResponse from(final Liquor liquor, final Long totalSalePrice) {
```suggestion
    public static LiquorSalePriceResponse from(
        @NonNull final Liquor liquor,
        @NonNull final Long totalSalePrice
    ) {
```

이건 지금까지 패턴에는 없던거지만 이렇게 해서 NPE를 메서드 수준에서 방지하는건 어떤가요? 지금도 `from()` 안에서 NPE가 뜨지만 해당 NPE는 실제로 참조해서 뜨는 NPE이고, `@NonNull`의 경우 lombok에 의해 발생하는 NPE라서 보다 빨리 예외를 알 수 있을 것 같아요. 

적용하라는 건 아니지만 생각이 궁금합니다!

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/dto/response/LiquorSaleQuantityResponse.java
> +public class LiquorSaleQuantityResponse {
`LiquorSalePriceResponse`의 코멘트 참고해주세요.

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/controller/StatisticsController.java
> @Scheduled methods must not take any arguments or return anything

위 경고 기억나시나요? `StatisticsController`에서 `updateStatisticsSales()`를 분리하고 별도의 Scheduler component를 선언하는게 나을 것 같아요~

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquor.java
> +public interface StatisticsLiquor {
1. interface 도메인은 무슨 역할을 하나요?
2. 현재 테스트 코드에서만 사용하는 것 같은데 맞나요?
3. JpaRepository에서 어떻게 List<StatisticsLiquor>를 반환하나요? StatisticsLiquor의 구현체가 없고 인터페이스만 있는데...? 신기하네요

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRepositoryImpl.java
> +public class StatisticsRepositoryImpl implements StatisticsRepository {
아니... 클래스 구조 왤캐 좋죠??? 처음엔 의아해서 물어보려고 작성하던 중에 큰 그림을 봐버렸습니다... 짱!!!

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
상수니까 UPPER_CASE로 작성하는게 좋을 것 같아요!

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +public class StatisticsRedisImpl implements StatisticsRedis {
캐시 TTL이 없어서 의아했는데, 캐시 업데이트는 evict 전략이 아닌 스케쥴러에 의한 update로 처리되는거 맞을까요?

2023-09-16 09:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquors.java
> +    private final Map<Long, Long> liquorIdAndValue;
Quantity와 Price가 동일한 일급 클래스를 사용하여 Long과 Value라는 이름을 사용하신 것 같은데 맞나요?

이로 인해 Value라는 것이 정확히 어떤 의미를 가지는지 이해하기 시간이 좀 걸리네요. 

이를 해결하기 위해서 StatisticsLiquors를 Generice 타입으로 변경하고 Quantity와 Price를 포장한 VO를 사용하면 어떨까요?

```java
new StatisticsLiquors<StatisticsQuantity>(statisticsLiquors);
```

아니면 다른 방법으로든 Value에 정확한 의미를 부여했으면 좋겠어요.

> 참고: Map을 valueByKey로 네이밍하면 편하더라구요.

2023-09-16 12:10 UTC, worldii approved these changes, later dismissed
킹 갓 제너럴 정세권

2023-09-16 12:10 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/statistics/service/StatisticsService.java
> +        StatisticsLiquors statisticsLiquors = statisticsRepository.findTop5LiquorIdAndSalePrice();
zzzzzz final 귀신이시네요

2023-09-16 12:10 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRepositoryImpl.java
> +        }
단순 궁금한건데용 캐시 추상화를 이용하지 않고, redis repository를  통해 데이터를 직접 액세스 하는 이유는 무엇인가요???

2023-09-16 12:10 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/statistics/dto/response/LiquorSaleQuantityResponse.java
> +        final Long totalSaleQuantity
of~

2023-09-16 12:10 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/statistics/dto/response/LiquorSalePriceResponse.java
> +    public static LiquorSalePriceResponse from(final Liquor liquor, final Long totalSalePrice) {
of

2023-09-17 01:28 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    }
해당 클래스는 statistics 관련 캐시만 사용하길래 수정해 보았웁니다^^

2023-09-17 01:38 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRepositoryImpl.java
> +        stopWatch.stop();
우선 StopWatch가 Spring 뿌레임 워크에서 제공하는 library 임과 동시에 좀 더 확장된 기능을 제공합니다. 원래 함수 단위별 test 하려고 stopWatch에 네이밍을 주어서 여러개 테스트 하느라 이것을 썼웁니다.
간단한 시간 테스트 하려면 Java에서 기본으로 제공하는 Java.currentTimeMilliseconds() 쓰는데 낫을것 같숩니다^^

2023-09-17 01:41 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquorsTest.java
> +@DisplayName("단위 테스트: StatisticsLiquors")
안그래도 통계 부분 테스트 어떻게 해야할지 고민이 많아서.. 주륵ㅠㅠ
브랜치를 하나 파서 제대로 작업할 생각입니다ㅜㅜ

2023-09-17 01:58 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/controller/StatisticsController.java
> +            = statisticsService.findTop5LiquorsBySalePrice();
chaining method 쓸 때 온점 (.) 을 다음 행에 써서 자연스럽게 저렇게 썼는데 보통 어떻게 쓰는지 궁금하긴 하네요🧐

2023-09-17 02:01 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/dto/response/LiquorSalePriceResponse.java
> +    public static LiquorSalePriceResponse from(final Liquor liquor, final Long totalSalePrice) {
좋아용~ 두분다 감솨합니다^^

2023-09-17 02:17 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/controller/StatisticsController.java
특별히 리턴 값이 없어서 void 로 수정했는데 이 부분은 어떻게 생각하시나요~?

2023-09-17 02:26 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquor.java
> +public interface StatisticsLiquor {
nativeQuery 특정 원하는 값만 받기 위해서 Projection 기능을 사용하는데 Class에 맵핑이 안되고 interface로만 맵핑이 가능하더라구요~ 정확한 원인은 좀 더 찾아봐야 할 것 같습니다! 관련해서 추가 학습 하고 공유드릴게요^^

관련 참고했던 자료 우선 링크 올릴게요^^
https://www.baeldung.com/spring-data-jpa-projections
https://velog.io/@rnqhstlr2297/%EC%8A%A4%ED%94%84%EB%A7%81-%EB%8D%B0%EC%9D%B4%ED%84%B0-JPA-Projections-%EB%B0%8F-Native-Query

2023-09-17 02:31 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
오잉?? "statistics" 요 부분이요??

2023-09-17 02:32 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +public class StatisticsRedisImpl implements StatisticsRedis {
네 맞숩니다. 처음에 TTL 처리를 해봤는데 결국 하루치 통계를 내기 전까지 값이 안바뀌어도 되는 값이 더라구요^^

2023-09-17 02:39 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquors.java
> +    private final Map<Long, Long> liquorIdAndValue;
이 부분도 정말 고민이 많았는데 특정 value 값 자체 (price, quantity) 추가로 서비스가 확장되면 재고 순으로 보고 싶을 수도 있고, 여러 값들에 의해 정의된 순서로 보고 싶을 경우가 생길것 같더라구요.
그래서 front 에서는 제대로된 naming으로된 response 값을 받도록 매번 추가할 생각이긴 한데 domain 부분까지 매번 확장될 때 마다 클래스가 생기면 부담이 될것 같더라구요.
우선 @whatasame 정규가 말한 부분을 제가 제대로 이해 못했을수도 있어서 여기에 한 번 더 코멘트 부탁드려요^^

2023-09-17 06:29 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquor.java
> +public interface StatisticsLiquor {
아하 특정 row의 일부 데이터만 가져오려면 Projection 기능을 이용해서 interface로 매핑을 해야하군요.

1. 그렇다면 왜 일부 데이터만 가져오는건가요? 모두 가져와서 getter로 빼면 되지 않을까요?
2. 혹시 커버링 인덱스를 활용하시는 건가요?

2023-09-17 06:41 UTC, whatasame requested changes
고생하셨습니다! 코멘트 밑 아래 메시지 하나 확인해주세요.

conversation을 resolved로 표기하셔서 피드백이 반영된 줄 알았는데 아직 아무런 커밋이 없어서 반영이 되지 않았네요. 피드백 반영 커밋 push한 후에 코멘트 달아주시면 덜 헷갈릴 것 같습니다.

2023-09-17 06:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquors.java
> +    private final Map<Long, Long> liquorIdAndValue;
> 그래서 front 에서는 제대로된 naming으로된 response 값을 받도록 매번 추가할 생각이긴 한데 domain 부분까지 매번 확장될 때 마다 클래스가 생기면 부담이 될것 같더라구요.

제가 이해한 요구 사항은 두 가지인 것 같습니다.

1. FE에서 제대로된 naming (e.g. value: 50이 아닌 quantity:50)으로 받도록 매번 추가해야한다.
2. 통계 항목이 추가 될 때마다 도메인 클래스가 추가된다.

두 요구사항 모두 Generic으로 해결할 수 있을 것 같습니다.

2023-09-17 06:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
```suggestion
    private static final String MAP_KEY_STATISTICS = "STATISTIC";
    private static final String STATISTICS_PRICE = "TOP5_SALE_PRICE";
    private static final String STATISTICS_QUANTITY = "TOP5_SALE_QUANTITY";
```

상수는 UPPER_CASE로 하지 않았나요? 근데 또 다른 레디스 자료를 찾아보니 다음과 같은 패턴을 쓰기도 하더라구요

> 상품 번호가 1이고 총 가격을 나타내는 Key에 대한 네이밍

```
product:1:total:price
```

> 기존(LiquorCtr)에서 사용하던 방식 (1번 상품의 클릭률)

```
LIQUOR_CTR-1
```

@hwihwi523 같이 보시면 좋을 것 같아요~

2023-09-17 06:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/controller/StatisticsController.java
1. 현재 수동 업데이트가 불가능하지 않나요? 통계 Entity의 PK가 년/일/월 복합키인데 하루에 1번만 실행할 수 있는 것 아닐까요?

2. 통계 관련 `update()` 메서드를 타고타고 가보니 JpaRepository에서는 INSERT를 수행하고 있네요. 메서드 명 수정이 필요합니다!

2023-09-17 07:58 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquor.java
> +public interface StatisticsLiquor {
총총총 지나가다가 말씀 드리자면,

row가 아닌 특정 컬럼만 조회하기 위해 interface로 매핑을 합니다!

그런데 집계 함수를 사용한 쿼리의 특성 상 원하는 컬럼을 지정해야 하므로 interface로 매핑하는 기능을 활용하신 것 같습니다!

2023-09-17 08:03 UTC, hwihwi523 submitted a review, later dismissed
짱!

2023-09-17 09:15 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
저도 관련해서 stack overflow 나 redis 공식 문서를 찾아봤는데
: 세미콜론 같은 경우 id 처럼 계층 관계가 있는 것인데 해당 부분은 statistics 라는 자료형에 각각 다른 key를 가지고 있어서 네이밍만 수정해도 괜찮을것 같네요^^
추가로 예시보면 보통 소문자로 구성되어있고 경우에 따라 camle case || snake case || hypen 형식으로 다양하게 쓴다고 하는데 이 부분은 다같이 논의해 봐도 좋을것 같습니다^^

https://stackoverflow.com/questions/6965451/redis-key-naming-conventions
https://fjolt.com/article/redis-hashes#:~:text=The%20naming%20convention%20of%20a,value%20key%20value%20....

2023-09-17 09:22 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquor.java
> +public interface StatisticsLiquor {
1. 굳이 현재 불필요한 값들을 다 select 할 필요가 없다고 판단했습니다^^
2. 따로 커버링 인덱스는 활용하지 않았어요~

재휘 의도 맞아요^^

2023-09-17 09:25 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/controller/StatisticsController.java
오호 컨트롤러에서 제거하고 Service 단에서 스케쥴링을 하는게 나을것 같네요^^
추가로 INSERT 와 UPDATE 작업을 둘 다 하고 있어서 이부분은 네이밍을 떠나서 개인적으로 분리를 해야할지 고민이네요
INSERT INTO ~ KEY UPDATE 쿼리 자체가 큰 범주에서 update 이기 때문에 우선 update 로 하기는 했습니다

2023-09-17 09:33 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
상수는 `STATISTICS`, `TOP5_SALE_PRICE`, `TOP5_SALE_QUANTITY`처럼 UPPER CASE로 하는 게 좋은 것 같습니다!

그리고 저도 세권이형과 마찬가지로 콜론으로 데이터를 다루진 않았었는데요!
그 이유는 계층 관계, 또는 prefix로 설정할 필요가 없었기 때문입니다!
왜냐하면 LIQUOR_CTR 이라는 Map 안에 (Key, Value) 쌍으로 저장하고 있기 때문이었습니다!

e.g. 요것처럼요!
LIQUOR_CTR : {
    1: RedisLiquorCtr(1, 2),
    20: RedisLiquorCtr(412, 313)
}

만약 Map을 쓰지 않았다면 저는 쩡규가 말한 대로 콜론으로 구분할 생각이었습니다!

e.g. 요로코롬요!
LIQUOR_CTR:1 : RedisLiquorCtr(1, 2)
LIQUOR_CTR:20 : RedisLiquorCtr(412, 313)

2023-09-17 09:41 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquors.java
> +    private final Map<Long, Long> liquorIdAndValue;
흠 우선 Generic 기준점에 맞게 지속적으로 클래스가 생성되야한다는 점과 정규가 말한 부분에 대한 이점을 아직 정확히 인지를 못하겠어요ㅜ
추가로 해당 부분을 리팩토링 하면서 List 형식으로 바뀌어서 네이밍은 바꾸지 않았습니다^^
해당 부분은 지속적으로 고민해서 나은 방향을 생각해 볼게요~

2023-09-17 10:55 UTC, whatasame approved these changes
고생하셨습니다!

2023-09-17 10:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquors.java
> +    private final Map<Long, Long> liquorIdAndValue;
> Generic 기준점에 맞게 지속적으로 클래스가 생성되야한다는 점

이게 무슨 뜻인가요? Generic은 여러 자료형을 하나의 클래스로 관리할 수 있어서 지속적으로 생성되는 일이 없지 않나요?

2023-09-17 10:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
그런데 왜 HashMap과 같은 구조인 Redis hashes를 사용하신건가요? 지금 상황에서는 Redis strings로 해결할 수 있지 않나요?

현재 hashes의 기능을 전혀 사용하지 않는데 메모리를 더 사용하는 hashes를 쓰는 이유가 있나요?

만약 strings로 사용한다면 `liquor_ctr:1`로 사용할 수 있을 것 같아요. 혹은 네이밍이 헷갈리니 `liquor:1:liquor_ctr`로 사용할 수 있을 것 같구요.

2023-09-17 10:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquor.java
> +public interface StatisticsLiquor {
> 집계 함수를 사용한 쿼리의 특성 상 원하는 컬럼을 지정해야 하므로

`sum(liquor_price)` 이런 컬럼은 존재하지 않으니까 *가 아닌 특정 컬럼을 지정할 수밖에 없다고 이해하면 되나요?

2023-09-17 10:55 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/controller/StatisticsController.java
좋아요^^

2023-09-17 10:58 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquor.java
> +public interface StatisticsLiquor {
> sum(liquor_price) 이런 컬럼은 존재하지 않으니까 *가 아닌 특정 컬럼을 지정할 수밖에 없다고 이해하면 되나요?

넵 그렇슴다! 집계 함수에 한정하지 않고 원하는 컬럼만 조회하기 위해서 사용합니다!

2023-09-17 11:04 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
LIQUOR_CTR hashes 안에서 상품 id와 CTR 정보를 key-value로 사용하고 있습니다.

어느 면에서 hashes의 기능을 전혀 사용하지 않고 있다고 생각하신 걸까요?

2023-09-17 11:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
LIQUOR_CTR 들을 하나의 HashMap에서 모아서 관리하고 있는데 모았다는 특징을 이용하고 있나요? 

그냥 개별의 LIQUOR_CTR들로 사용하면 더 적은 메모리로 똑같은 기능을 구현할 수 있지 않을까요?

2023-09-17 11:52 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
특정 정보만 범위 지어 관리하는 게.. 조금 걸리신다면.. 말씀대로라면 hashes는 언제 써야 하죠..?

https://mozi.tistory.com/522

그리고 간단히 한 번 참고해 보시면 좋을 것 같아요.

2023-09-17 12:47 UTC, whatasame requested changes
코멘트 확인해주세요~

2023-09-17 12:47 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/domain/StatisticsLiquor.java
> +public interface StatisticsLiquor {
제가 어리석었군요... 배워갑니다

2023-09-17 12:47 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
hashes가 strings보다 더 효율적이라는 사실을 몰랐습니다... 찾아보고 말할걸 죄송합니다!!!!!!!

2023-09-17 12:49 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/statistics/infra/StatisticsRedisImpl.java
> +    private static final String STATISTICS_QUANTITY = "top5SaleQuantity";
아닙미다!!! 저도 진짜 어렴풋이만 인지하고 있던 건데 요번 기회에 더 알아보게 되었읍니다!!!!!!! 감삼다!!!!!!!

2023-09-17 12:49 UTC, whatasame commented
이거 실수로 Request Changed 눌렀는데 unresolved 확인만 하라는 말만 건네고 approve 누르고 싶었습니다..

2023-09-17 12:49 UTC, whatasame submitted a review, later dismissed

2023-09-18 05:48 UTC, hwihwi523 approved these changes
짱!!

2023-09-18 05:48 UTC, merged