feat: 주문서 만료 시 COMPLETED 여부 확인 & 결제 완료 시 주문서 만료 이벤트 삭제
woowatechcamp/soolsool pull request #229
Opened 2023-09-17 13:40 UTC by hwihwi523

## ♻️ 변경 사항

1. 주문서 관련 이벤트 리스너 클래스를 삭제하고, ReceiptService에서 바로 구현한다.
2. 주문서 만료 시 결제완료된 주문서를 만료시키지 않도록 COMPLETED 여부를 확인한다.
3. 결제 완료 시 비동기 이벤트를 발행하여 Redis에 존재하는 주문서 정보를 삭제한다.

<br>

## 📌 참고 사항

처음에는 주문서 만료 이벤트 발생 시 COMPLETED가 아닌 것만 만료시키자는 생각을 했습니다.
그런데 이미 결제 완료된 주문서까지 매번 만료 이벤트를 발생시킬 필요가 있을까? 하는 생각이 들어서, 결제 완료 이후 Redis에서 주문서 정보를 삭제하는 로직도 추가했습니다.

요약하자면, 일반적인 경우 결제 완료 후 Redis에서 주문서 정보를 삭제합니다.
그러나 { 결제 완료 -> (비동기 이벤트) 주문서 정보 삭제 } 로직 사이에 만료 이벤트가 발생할 수 있기 때문에, 만료 이벤트가 발생했을 경우 COMPLETED 상태가 아닌지 확인하고 해당 주문서를 만료시킵니다.

### 발행해야 할 이슈
비동기 이벤트 큐 관련 설정

<br>

## 🎸 기타

closes #215

2023-09-17 20:05 UTC, worldii approved these changes
"BUNSANLOCKKINGGOD재휘님을 만나 내 인생이 달라졌다..."







분산락 이게 머지? ......


.
.
.
.
.
.
.
....
merge !

2023-09-17 20:05 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +        final RLock receiptLock = getReceiptLock(event.getReceiptId());
이거 분산락 거는 이유가 머에용?? 어차피 receiptExpiredEvent는 하나만 날아오지 않나용???  진짜 잘 몰라서 물어봅니다

2023-09-17 20:05 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/service/PayService.java
> +        locks.add(getReceiptLock(receiptId));
음 이거 동시성 고려할게 있나요? 어차피 update치는 거 밖에 없지 않나요?

2023-09-18 00:54 UTC, whatasame requested changes
분산 락을 안 써도 동시성을 해결할 수 있는 부분들 코멘트로 남겼습니다!

2023-09-18 00:54 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/payment/service/PayService.java
> +        locks.add(getReceiptLock(receiptId));
그러게요 Member Lock, Receipt Lock 둘 다 RDB에서 네이티브 update로 쓰기락 걸 수 있을 것 같아요.

dirty read로 해결하는 코드가 상당히 많았군요...

2023-09-18 00:54 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +        );
이 부분도 dirty check가 아닌 update로 변경하면 될 것 같네요!

2023-09-18 00:54 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/event/listener/ReceiptExpiredEventListener.java
EventListener가 있는게 Event를 처리하는 곳을 바로 알 수 있어서 좋았는데 Service로 통합한 이유가 있을까요?

2023-09-18 00:54 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/repository/redisson/ReceiptRedisRepository.java
> +    }
5분 만료 이벤트를 없애기 위해서 remove 하는 코드 맞나요?

2023-09-18 00:54 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +    private static final long LOCK_LEASE_TIME = 3L;
레디스가 단순 get, set 처리는 1초에 10만개를 처리한다고 하더라구요. 3초라는 시간을 선정한 이유가 있을까요?

3초라는 시간이 레디스에게는 엄청 긴 시간인 것 같은데 다른 시간 단위도 고려하면 좋을 것 같아요.

2023-09-18 00:54 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +            );
```sql
UPDATE receipt
SET status = 'expired'
WHERE id = 1 AND status != 'completed';
```

이 부분도 dirty check가 아닌 native query로 가능할 것 같아요!

2023-09-18 06:04 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +        final RLock receiptLock = getReceiptLock(event.getReceiptId());
결제 완료 로직과 만료 이벤트 로직이 맞물릴 경우 동시성 문제가 발생할 수 있읍니다!

결제 완료 로직과 만료 이벤트 로직이 맞물리면 두 로직 모두 처음에 상태가 IN_PROGRESS인 주문서를 select 합니다!

이때 결제 완료 -> 만료 이벤트 순서로 처리될 경우 COMPLETED 됐음에도 불구하고 만료 이벤트에서 처음에 읽어온 값이 IN_PROGRESS라서 만료 처리를 해버립니다!

2023-09-18 06:09 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/payment/service/PayService.java
> +        locks.add(getReceiptLock(receiptId));
> 음 이거 동시성 고려할게 있나요? 어차피 update치는 거 밖에 없지 않나요?

위에 코멘트 답변 달아 두었읍니다!

> 그러게요 Member Lock, Receipt Lock 둘 다 RDB에서 네이티브 update로 쓰기락 걸 수 있을 것 같아요.
> 
> dirty read로 해결하는 코드가 상당히 많았군요...

아닙니다! update 락으로 동시성 문제를 제어할 수 있는 건 += 쿼리입니다!
이때 += 쿼리를 사용할 수 있는 것은 멤버 마일리지 차감과 술 재고 차감하는 기능인데, +=으로만 동시성을 제어할 경우 마일리지와 재고가 부족할 때의 로직을 도메인에서 처리하기 힘들어집니다!

그리고 주문서 상태의 경우 += 쿼리를 적용할 수가 없습니다!

2023-09-18 06:22 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +        );
위 코멘트 참고해 주세요!

2023-09-18 06:25 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/event/listener/ReceiptExpiredEventListener.java
서비스 코드만 보고도 어느 메서드가 이벤트를 담당하는 메서드인지, 요청을 처리하는 메서드인지 명확히 표현할 수 있을 것 같아서 바꾸어 보았습니다!

그런데 더 생각해 보니 이벤트가 발생했을 때 호출되는 로직이 서비스마다 분산되어 이벤트 로직을 파악하기 힘든 일이 일어날 수 있을 것 같아여......... 코멘트 보고 생각 정립을 다시 할 수 있게 됐네요 감사합니다 흡.... 고쳐두도록 하겠읍니다!

2023-09-18 06:35 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/repository/redisson/ReceiptRedisRepository.java
> +    }
옙 맞슴둥!

2023-09-18 06:37 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +    private static final long LOCK_LEASE_TIME = 3L;
단순 처리하는 건 빠르지만 로직을 모두 처리한 후 락을 해제하는 데까지 시간이 걸리기 때문입니다!

결제 로직에서 카카오페이 API를 호출하고 있는데 로직을 처리하는 도중 락이 반납되면 안 되기 때문에 위와 같이 3초로 설정했습니다!

2023-09-18 06:40 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +            );
달아주신 코멘트의 맥락을 파악해 보면 락을 걸지 않고 동시성 문제를 제어하기 위해서 update 네이티브로 바꾸자고 하시는 것 같습니다!

혹시 제 생각이 맞다면 위의 답변에서 말씀드렸듯 주문서 상태 변경의 경우 += 쿼리를 사용할 수 없기 때문에 네이티브로 바꾸어도 동시성을 직접 처리해 주어야 합니다!

반대로 제 생각이 틀려서 단순히 더티체킹이 아닌 네이티브 쿼리를 이용하자는 말씀이셨다면, 저는 JPA의 기능을 조금 더 활용했으면 하는 바람입니다!

2023-09-18 06:57 UTC, whatasame requested changes
일단 재고 관련 코멘트 빼고 코멘트 달았습니다. 확인해주세요!

2023-09-18 06:57 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +            );
> 락을 걸지 않고 동시성 문제를 제어하기 위해서 update 네이티브로 바꾸자

동시성 문제가 발생하는 원인은 dirty check를 사용하기 때문입니다! 이를 해결하기 위해서 두 가지 방법이 있다고 생각합니다.

* select 비관적 락
* 다른 락 사용 -> 현재 방법: Redis 분산락

현재 JPA로 가져와서 아무것도 하지 않고 단순히 조건 비교만 한 후 dirty check로 업데이트를 하는데, 마지막 update 시에도 락이 걸립니다. 따라서 해당 로직을 수행하기 위해 Redis 락 1개, RDB 락 1개 총 2개를 사용하고 있습니다. 😭

만약에 이를 제안한 native query로 변경한다면 Redis 락과 select 쿼리를 없앨 수 있을 것 같습니다. 쿼리 1개, 락 1개로 끝낼 수 있는 일을 JPA 기능을 이용함으로써 쿼리 2개, 락 2개로 늘렸다고 생각하는데 어떤가요?

2023-09-18 06:57 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +    private static final long LOCK_LEASE_TIME = 3L;
아하 그럼 지연 쓰기의 경우 단순한 set 연산이 매우 빈번하게 발생하는데 해당 경우에는 시간을 줄여도 될 것 같아요. 어떤가요??

2023-09-18 06:57 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +        final RLock receiptLock = getReceiptLock(event.getReceiptId());
```sql
UPDATE receipt
SET status = 'expired'
WHERE id = 1 AND status != 'completed';
```

이러한 쿼리로 해당 문제를 해결할 수 있지 않을까요?

2023-09-18 06:57 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +        );
```sql
UPDATE receipt
SET status = 'expired'
WHERE id = 1 AND status != 'completed';
```

이것도 이렇게!

2023-09-18 07:00 UTC, worldii submitted a review, later dismissed
와오고심히 생각한게 느껴집니다~~~~

2023-09-18 07:00 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/service/PayService.java
>          final RLock multiLock = redissonClient.getMultiLock(
그럼 반대로 여기서도receipt 가 expired 되었는지 확인해줘야 하는 로직이 필요하지 않을까요 ??

2023-09-18 07:00 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/payment/service/PayService.java
>          final RLock multiLock = redissonClient.getMultiLock(
그리고 생각이 든건데 이거는 동시성관련한 오류가 거의 안날꺼 같은데 낙관적락을 사용하는 방법도 있지 않나요???

2023-09-18 07:20 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +            );
일단 dirtychecking을 해야한다는 것은 저는 동의합니다. 
왜냐면 order 부분을 진행할 때,만약 만료 로직이 발행되어서 expired가 되었다면, 오더를 실행시키면 안된다고 생각해요.
근데 이 부분이 지금 approve에 빠진거 같아요. 그래서 update 네이티브 쿼리로 날리게 되면 이런 예외 처리를 못해줄거같아요. 
분산락, 비관락을 사용할 수 있겠지만, 동시성 오류가 크게 안날거같아요 5분이란 시간에 딱 만료 로직과 오더 부분 로직이 발행되는 경우는 거의 없을 거 같거든요. 낙관 적락을 사용하게 되면 select 하는 시점에 달라지는 것을 확인해서 예외를 터지게 하니까 만료 로직때 select를 해올때 inprogress 상태일때만 바꿔주고 반대로  order 부분에서도 inprogress 상태일 때만 바꿔주는 방식으로 진행하면 되지 않을까요????

2023-09-18 07:58 UTC, worldii commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +            );
흠.. 근데 낙관적락하고 트랜젝션하고 같이 못쓰인다는걸 지금알았네요ㅋ쿠ㅜ 롤백처리를 따로 해줘야 하는데 이에 대한 로직을 따로 작성해줘야 하네용 흠.. 그럼 그냥 분산락이 젤 맞는거 같은데요:??????

2023-09-18 08:34 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +            );
쩡규 :
> 현재 JPA로 가져와서 아무것도 하지 않고 단순히 조건 비교만 한 후 dirty check로 업데이트를 하는데, 마지막 update 시에도 락이 걸립니다. 따라서 해당 로직을 수행하기 위해 Redis 락 1개, RDB 락 1개 총 2개를 사용하고 있습니다. 😭

말씀해 주신 요 부분은 진짜 와방 동의합니다!!!
그런데 제 생각과 다른 게 진짜 쬐끔 있는데요!

1. 락으로 인한 병목 현상의 발현 가능성
저는 락을 두 개 물어도 괜찮다고 생각을 하는 게, 병목 현상이 발생할 거라 생각하지 않습니다! 왜냐하면 주문서 상태 변경과 관련된 것은 한 번에 여러 요청이 몰리지 않기 때문입니다! 그럼에도 불구하고 제가 사전에 주문서 관련하여 RLock을 추가로 걸어준 것은 혹시 모를 상황을 대비하고자 하는 것이었습니다!

2. 조회 쿼리를 줄이는 것
저번에 지하철 미션 때 리뷰어님이 단순 조회는 병목 현상에 크게 일조하지 않는다고 하셔서 저는 쿼리 2번 날리는 요 부분은 가볍게 생각하고 넘어갔습니다!

3. 네이티브 쿼리 지양
추가로, 네이티브 쿼리를 가급적 지양하고 싶은데요, 왜냐하면 DB에 의존적이게 될뿐더러 로직을 쉽게 파악하기 힘들다고 생각합니다!
만약 다른 DB로 변경하는 경우, JPA가 만들어 준 쿼리가 아니기 때문에 모두 수정해야 하고, 게다가 네이티브 쿼리 하나로 퉁치기 때문에 쿼리를 봐야 로직이 이해가 된다는 점이 조금 걸립니다! 따라서 JPA 기능을 이용함으로써 포기해야 하는 게 거의 없다고 생각해서 네이티브 쿼리보단 더티체킹을 이용해 객체지향적 이점을 취하는 게 좋다고 생각합니다!

결론적으로는.. 점차 네이티브 쿼리에 의존적인 게 여럿 생기는 것 같습니다.. 클릭수나 노출수 반영하는 것도 그렇구요..
뿐만 아니라 락을 걸어서 발생하는 병목 현상은 거의 없을 거라 생각하여 성능적으로도 문제가 없다 생각하구요..!
그래서 저는 현 상태를 유지하는 게 객체지향적 이점도 챙기고, 서비스 로직도 쉽게 파악할 수 있을뿐더러 DB 의존성도 줄일 수 있다고 생각합니다..!

2023-09-18 08:37 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/payment/service/PayService.java
>          final RLock multiLock = redissonClient.getMultiLock(
낙관적 락 정말 좋은 아이디어인 것 같습니다!

만료 이벤트, 결제 로직 둘 중 하나만 발생해야 한다는 점에서 낙관적 락도 좋은 것 같습니다!

그런데 요 이벤트에선 만료 이벤트와 결제 로직이 맞물리는 병목 현상이 발생할 거라 생각하지 않기도 해서, 다른 락들과 같은 락을 사용함으로써 한 번에 관리하고자 했습니다!!

2023-09-18 08:37 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +    private static final long LOCK_LEASE_TIME = 3L;
오 그건 좋은 아이디어네요!!! 감삼다!!!!

2023-09-18 08:39 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/payment/service/PayService.java
>          final RLock multiLock = redissonClient.getMultiLock(
> 그럼 반대로 여기서도receipt 가 expired 되었는지 확인해줘야 하는 로직이 필요하지 않을까요 ??

짱입니다... 짱이에요...

2023-09-18 12:49 UTC, whatasame approved these changes
고생하셨습니다. 저는 단순한 UPDATE 정도는 JPQL로 처리해도 이해하기 쉽다고 생각했습니다. 

분산 락을 너무 과하게 쓰고 있는 건 아닐까? 하는 노파심에 남긴 코멘트였는데, 다른 분들의 의견도 궁금합니다.

2023-09-18 12:49 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +            );
> 다른 DB로 변경하는 경우, JPA가 만들어 준 쿼리가 아니기 때문에 모두 수정해야 하고, 게다가 네이티브 쿼리 하나로 퉁치기 때문에 쿼리를 봐야 로직이 이해가 된다는 점이 조금 걸립니다!

실제로 데이터베이스가 바뀔 일은 거의 0에 수렴하고 JPQL을 이용하면 쿼리를 추상화하였기 때문에 쿼리를 수정할 필요는 없을 것 같습니다. 하지만 객체에 메시지를 보낸다는 객체 지향 프로그래밍의 취지와 동떨어진다는 점에는 동의합니다!

사실 저도 비슷하게 생각했었는데요. 어떻게보면 Redis 분산 락 없이 해결할 수 있는 문제를 Redis를 사용함으로써 관리 포인트가 더 늘어나지 않을까싶어 우려하는 마음에서 코멘트를 달았습니다.

2023-09-18 13:39 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/receipt/service/ReceiptService.java
> +            );
맞습니다 ㅜㅜ 사실 DB를 바꿀 일이 없는데다가 바꾼다고 해도 문법이 다른 이종 DB로 바꾸는 일은 없을 것 같습니다!
다만 네이티브 쿼리의 단점으로 흔히 언급되는 것 중 하나여서 JPQL로 불가능한 것이나 성능을 크게 저하시키는 게 아니라면 해당 부분을 지양하고자 했습니다!
감삼둥!!

> ... JPQL을 이용하면 쿼리를 추상화 ...

(네이티브 쿼리를 사용할 경우 JPQL이 아닌 SQL이 나가게 됩니다!)

2023-09-18 13:40 UTC, merged