Member 추가, 삭제, 조회, 수정 추가
woowatechcamp/soolsool pull request #51
Opened 2023-08-17 12:45 UTC by jjungsk

## ♻️ 변경 사항

* 멤버 추가
* 멤버 삭제
* 멤버 조회
* 멤버 수정
* test code 추가

<br>

## 🎸 기타

* closes #23

2023-08-17 14:20 UTC, hwihwi523 reviewed
이외에 테스트 코드에서 간혹 given, when, then 주석이 빠진 경우가 보이던데 붙여주면 좋을 것 같아요!

2023-08-17 14:20 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/member/domain/Member.java
> +    public void update(MemberModifyRequest memberModifyRequest) {
final !!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/member/domain/MemberRole.java
> +    public MemberRole(MemberRoleType name) {
final !!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/member/domain/vo/MemberMileage.java
> +    public MemberMileage(String mileage) {
final!!!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/member/dto/request/MemberModifyRequest.java
> +//@RequiredArgsConstructor
주석 버려도 되지 않을까요????

2023-08-17 14:20 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/member/dto/request/MemberModifyRequest.java
> +//@RequiredArgsConstructor
내용 삭제를 의미하는 겁니다!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/main/resources/data.sql
> +values (2, 'VENDOR');
한 줄에 한 명령 씩 해주세요잉

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +        ExtractableResponse<Response> response = RestAssured.given()
given은 다음 줄에 이어 붙여 주세여!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +        ExtractableResponse<Response> response = RestAssured.given()
요 given도 다음 줄로 이어 붙여 주세요!!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .body(memberAddRequest)
contentType, body는 given에 있으면 좋을 것 같아요!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .log().all()
한 줄로 잇는 건 어떠신가요!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .get("/members")
이것도 한 줄로 이으면 좋을 것 같아요!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .log().all()
이것도 한 줄로!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .log().all()
이것도 given 다음으로 넘기고 한 줄로 이어 붙여 주세요!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .patch("/members")
contentType, body는 given으로, when과 patch는 한 줄로 하는 건 어때요??

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .log().all()
요것도 한 줄..!?

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .log().all()
같은 형식으로..!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/support/TestFixture.java
> +            .then()
요것도 같은 형식..!!

2023-08-17 14:20 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/unit/domain/MemberTest.java
> +
클래스 마지막 개행은 빼주세요!

2023-08-17 14:25 UTC, whatasame requested changes
고생하셨습니다. 첫 기능 구현이라 팀 단위로 의논할 것도 작성해서 코멘트 수가 좀 많은데 이해하기 힘든 내용은 코멘트 달아주세요!

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/controller/MemberController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
저는 개행으로 코드의 흐름을 구분하는 편이라 return 앞에 개행을 추가하는 편인데 이에 관해 이야기를 해봐야할 것 같아요.

또, 201의 경우 Location header에 접근할 수 있는 URL을 포함해야하는데 지금처럼 조회 endpoint를 제공하지 않는 경우 불가능하므로 200이 적절한 것 같습니다.

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/controller/MemberController.java
> +        Long userId = 1L;
request dto가 아닌 매직넘버 1을 사용하는 이유가 있나요?

또, 회원에 대한 단어는 member를 사용하는데 user는 다른 의미가 있을까요?

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/dto/request/MemberAddRequest.java
> +    ) {
request dto에 Builder가 필요한 이유가 있나요? @JsonCreator와 생성자를 이용하면 될 것 같아요.

또, 현재 회원 역할을 String으로 저장하고 있는데 생성자 내부에서 `MemberRoleType.valueOf()`를 이용하여 지정하면 controller의 불필요한 `MemberRole` 인자를 줄일 수 있어요.

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/domain/Member.java
> +
ER diagram과 순서를 맞춰준 건가요? 섬세함 좋아요 👍

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/domain/Member.java
> +    public static Member of(MemberRole memberRole, MemberAddRequest memberAddRequest) {
MemberRole 인자를 줄일 수 있을 것 같아요. MemberAddRequest 코멘트 참고해주세요.

또, domain이 dto를 알고 있는게 맞을까요? `Member.of()`보단 `MemberAddRequest.to()`가 적절할 것 같습니다.

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/domain/Member.java
> +    public void update(MemberModifyRequest memberModifyRequest) {
도메인이 dto와 의존 관계를 맺는건 부적절한 것 같아요.

또, update라는 하나의 함수가 너무 많은 역할을 가지고 있고 이름이 모호하네요. 하나의 함수가 하나의 필드를 수정하도록 변경하는게 좋을 것 같아오.

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/domain/MemberRole.java
> +    }
하나의 인자만 받는 생성자에서 builder가 있는게 어색해보여요. 혹시 특별한 이유가 있을까요?

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/domain/vo/MemberMileage.java
> +    }
편의성 생성자 좋습니다~

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/domain/vo/MemberRoleType.java
> +    CUSTOMER("고객"),
wiki 명세에는 구매자로 되어있는데요. 둘 중에 하나로 합의가 필요할 것 같아요.

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/dto/request/MemberAddRequest.java
> +    @Size(max = 255, message = "email 길이가 너무 깁니다.")
validation 메시지도 매직넘버처럼 느껴집니다..! 

해당 메시지는 Member VO에서도 사용하고 있는데요.  `MemberErrorCode`의 enum 상수에서 메시지를 가져와 사용하는 것에 대해 의논해봐요. (현재 해당 branch가 pr에 있긴 합니다 🙄)

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/dto/request/MemberModifyRequest.java
> +//@RequiredArgsConstructor
모든 field가 final이니 builder를 삭제하고 이걸 사용하는게 더 적절한 것 같아요

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/dto/response/MemberFindResponse.java
> +    }
똑같이 `@RequiredArgsConstructor`가 적절해보입니다.

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/service/MemberService.java
> +            .orElseThrow(() -> new SoolSoolException(DefaultErrorCode.MEMBER_NO_ROLE_TYPE));
1번이 기본 역할인 구매자인 것 같은데 기본 역할은  repository에서 가져오는 것이 아니라 static field로 가지고 있으면 좋을 것 같아요.

또, 예외 코드도 추후에 MemberErrorCode로 옮겨주시면 좋을 것 같아요.

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/member/service/MemberService.java
> +        member.update(memberModifyRequest);
modify, update, add, create와 같이 비슷한 용어를 하나로 정하면 코드를 사용할 때 예측하기 좋을 것 같은데 이에 대해 의논해봐요.

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/exception/DefaultErrorCode.java
>      ;
혹시 몰라 다시 한 번 메모용으로 작성해요. 나중에 MemberErrorCode로 옮기기!

2023-08-17 14:25 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/global/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<ErrorResponse> handleValidationException(
protected 좋아용

위에 코멘트가 안달리는데 handleShoppingExeption을 SoolSool로 업데이트 부탁드려요!

2023-08-17 14:25 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +@DisplayName("멤버 : 컨트롤러 테스트")
회원이라는 용어로 통일하면 좋을 것 같습니다. 또, 컨트롤러 테스트라고 하니 단위테스트 인 것 같아서 인수 테스트가 더 적절할 것 같아요

2023-08-17 14:25 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/support/TestFixture.java
> +public class TestFixture {
이름이 보다 명확하면 좋겠어요 MemberFixture는 어떠신가요?

2023-08-17 14:25 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/support/TestFixture.java
> +    public static ExtractableResponse<Response> addMember() {
Fixture는 고정된 값을 넣기 때문에 메서드 이름에서 어떤 값을 사용하는지 드러나면 좋겠어요

2023-08-17 14:25 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/support/TestHelper.java
> +    public static Member getMember() {
반대로 Helper는 매개 변수로 유연하게 사용할 수 있는게 적절해 보여요

2023-08-17 14:25 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/support/TestHelper.java
> +public class TestHelper {
Helper 이름도 구체화 하는게 좋을 것 같네요

2023-08-17 14:25 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/unit/domain/MemberTest.java
> +class MemberTest {
다른 pr에서 이 테스트를 다루고 있어서 삭제해도 좋을 것 같아요. 물론 이 테스트가 왜 생겼는지는 잊지 않았습니다 😭

2023-08-17 14:25 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/unit/service/MemberServiceTest.java
> +class MemberServiceTest {
해피 케이스는 인수 테스트에서 충분히 검증되고 있어 중복되는 것 같네요. 단위 테스트에서는 예외 케이스를 검증하는게 좋아보이는데 의논해보죠!

2023-08-17 14:25 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/acceptance/AcceptanceTest.java
> +@Sql("classpath:data.sql")
test/resources에 data.sql을 넣으면 자동으로 실행하지 않나요?

2023-08-17 16:24 UTC, jjungsk commented on src/main/resources/data.sql
> +values (2, 'VENDOR');
google convention 때문인지 저장하면 자동으로 줄바꿈이 됩니다ㅜ

2023-08-17 16:28 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .log().all()
log().all() 은 따로 있는걸 선호하는 편이라 어떤게 나을까요?

2023-08-17 16:28 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/integration/controller/MemberControllerTest.java
> +            .get("/members")
이 부분은 다같이 모였을 때 살짝 통일하는것도 좋은것 같습니다^^

2023-08-17 16:32 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/controller/MemberController.java
> +        Long userId = 1L;
나중에 jwt token을 파싱하여 memberId를 받아오기 때문에 우선 임의의 userId = 1L을 받았는데 나중에 수정은 할거지만 memberId로 우선 수정하는게 나을것 같네요~

2023-08-17 16:33 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/dto/request/MemberAddRequest.java
> +    ) {
@Bulder 부분을 한번 다같이 논의해 보려고 했는데 지금 생성자가 아닌 대부분 builder pattern을 사용해서 통일시키면 어떨까 하는 생각에 우선 적용해 보았습니다^^

2023-08-17 16:35 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/dto/request/MemberAddRequest.java
> +    ) {
추가로 MemberRoleType을 우선 연 경우는 현재는 default로 CUSTOMER를 저장하지만 추후에 VENDOR를 front 단에서 저장할 수 있지 않을까? 하는 생각에 우선 열어두었습니다. 이 부분도 같이 의논해보면 좋을것 같네요

2023-08-17 16:37 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/domain/Member.java
> +    public static Member of(MemberRole memberRole, MemberAddRequest memberAddRequest) {
오~ 이 부분은 조금 궁금하긴 했는데 보통 DTO 애서 DOMAIN으로 변환 하나요?

2023-08-17 16:38 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/domain/Member.java
> +    public void update(MemberModifyRequest memberModifyRequest) {
uopdate 부분인 경우 현재 프론트에서 3가지를 변경할 수 있게 열어뒀는데 보통 update로 3가지 인자를 받는 dto를 넘기지 않나요?? 어떻게 진행하는 것이 나을지 이 부분은 애매하네요 그렇다면

2023-08-17 16:39 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/domain/MemberRole.java
> +    }
각 클래스별 어떤것은 생성자 어떤것은 빌더패턴이 좀 애매한것 같아 빌더 패턴으로 통일해 보는것이 좋은것 같은데 이 부분은 다 같이 한번 의논해 봐도 좋을것 같네요^^

2023-08-17 16:40 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/domain/vo/MemberRoleType.java
> +    CUSTOMER("고객"),
이 부분은 제가 wiki를 제대로 확인을 못했네요 수정하겠습니다^^

2023-08-17 16:40 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/dto/request/MemberAddRequest.java
> +    @Size(max = 255, message = "email 길이가 너무 깁니다.")
안그래도 이부분 같이 의논해 봐야할것 같았는데 좋아요^^

2023-08-17 16:42 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/service/MemberService.java
> +            .orElseThrow(() -> new SoolSoolException(DefaultErrorCode.MEMBER_NO_ROLE_TYPE));
ErrorCode를 분리하자는 말이죠?

2023-08-17 16:42 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/member/service/MemberService.java
> +        member.update(memberModifyRequest);
좋아요^^

2023-08-17 16:44 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/global/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<ErrorResponse> handleValidationException(
handleShoppingException -> soolSoolException ???

2023-08-17 16:45 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/support/TestFixture.java
> +public class TestFixture {
이 부분도 의논해보면 좋을것 같습니다. 도메인 별로 나눌지 등등!??

2023-08-17 16:46 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/support/TestFixture.java
> +    public static ExtractableResponse<Response> addMember() {
흠.. 어떻게 바꾸는게 나을까요? 멤버를 추가한다는 의미에서 addMember 로 하기는 했습니다~

2023-08-17 16:46 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/support/TestHelper.java
> +    public static Member getMember() {
이 부분도 같이 얘기해봐요^^

2023-08-17 16:48 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/unit/service/MemberServiceTest.java
> +class MemberServiceTest {
우선 시간이 부족해 모든 예외 사항에 테스트를 추가하지 못했습니다. 따로 코멘트를 남겼어야 했는데 추후 리팩토링 진행할게요^^

2023-08-17 16:48 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/acceptance/AcceptanceTest.java
> +@Sql("classpath:data.sql")
우선 이 부분은 지금 리팩토링 중인데 흠..ㅠ,ㅠ

2023-08-18 07:01 UTC, whatasame approved these changes
굿굿

2023-08-18 07:01 UTC, merged