feat: 상품 조회 (상세 정보, 목록)
woowatechcamp/soolsool pull request #64
Opened 2023-08-18 08:20 UTC by hwihwi523

## ♻️ 변경 사항

```
ex)
### docs: PULL_REQUEST_TEMPLATE.md 작성 ... [a6684f7](https://github.com/five-uys/test/commit/7625214be558f7496cca1dec633f02942799dff1)

* PR 생성 시 자동으로 적용될 템플릿
* ...
```
### 술 정보 상세 조회

> 조회 정보
> 1. 술 ID
> 2. 술 이름
> 3. 가격
> 4. 이미지 경로
> 5. 재고
> 6. 도수
> 7. 용량

### 술 목록 조회

> 조회 정보 (리스트)
> 1. 술 ID
> 2. 술 이름
> 3. 가격
> 4. 이미지 경로
> 5. 재고

1. 최신순 조회
2. 조건 검색 (조합 가능)
    - 술 종류
    - 지역
    - 판매 상태
    - 브랜드

<br>

## 📌 참고 사항

```
ex)
* 결제 부분 로직이 복잡한데, ~~~ 이유로 ~~~ 를 구현하기 위해 불가피했읍니다.
* ...
```

<br>

## 🎸 기타

```
ex) 닫을 이슈가 있다면,
closes #이슈번호
```
closes #53

2023-08-18 08:49 UTC, jjungsk requested changes
굳~~ 많이 배웠습니다^^
리뷰 빠르게 한번만 확인 부탁드려유

2023-08-18 08:49 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        return ApiResponse.of(LiquorResultCode.LIQUOR_LIST_FOUND, response);
ResponseEntity<ApiResponse<>> 형식으로 통일하면 좋을것 같습니다^^

2023-08-18 08:49 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/converter/LiquorBrewTypeConverter.java
> +}
요런게 있었군요 굳~~!

2023-08-18 08:49 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
>  @RequiredArgsConstructor
@Transactional 확인 부탁드려요~!^^

2023-08-18 08:49 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +                liquor.getVolume().getVolume()
요거는 개인적인 취향이기도 한데 Response Dto 안에서 Liquor Domain을 받아 정적 팩토리 메서드로 리턴하면 서비스 코드가 깔끔할것 같습니다^^

2023-08-18 08:49 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +                .collect(Collectors.toList());
요 부분도 한번 생각해 보면 좋을것 같습니다^^

2023-08-18 08:49 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/core/liquor/service/LiquorService.java
> +    }
오홍!

2023-08-18 08:49 UTC, jjungsk commented on src/main/java/com/woowacamp/soolsool/global/config/WebConfig.java
> +    }
굳~ 저도 적용해 보겠습니다^^

2023-08-18 08:49 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/integration/repository/LiquorTypeRepositoryTest.java
> +                .forEach(type -> liquorTypeRepository.save(new LiquorType(null, type)));
tab 2번 된거 같은디요!?

2023-08-18 08:49 UTC, jjungsk commented on src/test/java/com/woowacamp/soolsool/integration/repository/LiquorTypeRepositoryTest.java
> +                .orElseThrow();
얘도!?

2023-08-19 06:47 UTC, hwihwi523 reviewed
별 거 없네요!! 좋습니다!!!!

2023-08-19 06:47 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +        final LiquorDetailResponse response = liquorService.liquorDetail(liquorId);
```suggestion
        @PathVariable final Long liquorId
    ) {
        final LiquorDetailResponse response = liquorService.liquorDetail(liquorId);
```

2023-08-19 06:47 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +            brand, sortPageable);
```suggestion
            status, brand, sortPageable);
```

2023-08-19 06:47 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/repository/LiquorRegionRepositoryTest.java
> +        LiquorRegion 경기도 = liquorRegionRepository.findByType(GYEONGGI_DO).orElseThrow();
.orElseThrow를 다음 줄로 넘겼으면 좋겠어요!!!
```suggestion
        LiquorRegion 경기도 = liquorRegionRepository.findByType(GYEONGGI_DO)
            .orElseThrow();
```

2023-08-19 06:47 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/repository/LiquorStatusTypeRepositoryTest.java
> +            .findByType(ON_SALE).orElseThrow();
첫 줄엔 findByType을 두고 orElseThrow는 두 번째 줄에 있었으면 좋겠어요!!!!
```suggestion
        LiquorStatus 판매중 = liquorStatusRepository.findByType(ON_SALE)
            .orElseThrow();
```

2023-08-19 07:08 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +            brand, sortPageable);
```java
final List<LiquorElementResponse> response = liquorService
            .liquorList(brew, region, status, brand, sortPageable);
```

이렇게 바꿨는데 어떤가요?

2023-08-19 07:11 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/controller/LiquorController.java
> +            brand, sortPageable);
훨씬 좋아요. 짱. 👍

2023-08-19 07:13 UTC, merged