refactor: global 패키지 리팩터링
woowatechcamp/soolsool pull request #74
Opened 2023-08-19 13:20 UTC by whatasame

## ♻️ 변경 사항

* exception 패키지에 있는 code 클래스를 별도의 code 패키지로 이동
* Liquor 관련 Converter 설정을 global에서 분리
* ShoppingException 삭제

<br>

## 📌 참고 사항

1. `DefaultErroCode`와 `GlobalErrorCode`의 역할이 모호한데 둘 중 하나로 합쳐서 구체화된 이름이 필요한 것 같아요.
2. `AttributeConverter`와 `Converter` 클래스가 모두 Converter로 끝나는게 애매모호 합니다잉~

<br>

## 🎸 기타

closes #71

2023-08-19 14:53 UTC, hwihwi523 requested changes
대체로 이중 탭이 된 코드가 좀 보여요!! 그 외에 로직이나 다른 부분엔 이상 없습니다!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/CartItem.java
> +            final int quantity
탭이 두 번 된 것 같아여!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/config/LiquorBrewTypeConverter.java
> +                .orElse(null);
이중 탭이 된 것 같아요!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/config/LiquorConfig.java
> +}
파일은 개행으로 끝나야 한다고 알고 있습니다!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/config/LiquorRegionTypeConverter.java
> +                .orElse(null);
이중 탭!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/config/LiquorStatusTypeConverter.java
> +                .orElse(null);
이중 탭!!!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/global/exception/GlobalExceptionHandler.java
> +            final MethodArgumentNotValidException exception
이중 탭이요!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorAlcoholTest.java
> +                () -> assertThat(origin).doesNotHaveSameHashCodeAs(different)
이중 탭이요!!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorAlcoholTest.java
> +                .hasMessage("술 도수는 0 이상 실수여야 합니다.");
한 줄에 하나씩 쓰는 건 어뗘요????

```suggestion
        assertThatCode(() -> new LiquorAlcohol(-1.2))
            .isExactlyInstanceOf(SoolSoolException.class)
            .hasMessage("술 도수는 0 이상 실수여야 합니다.");
```

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorNameTest.java
> +                .hasMessage("술 이름은 null이거나 공백일 수 없습니다.");
이중 탭이여!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorPriceTest.java
> +                .doesNotThrowAnyException();
이 중 탭 !!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorPriceTest.java
> +                .hasMessage("술 가격은 0 미만일 수 없습니다.");
이중 탭이에요!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorPriceTest.java
> +                .hasMessage("술 가격은 null일 수 없습니다.");
이중 탭임다!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorPriceTest.java
> +                () -> assertThat(origin).doesNotHaveSameHashCodeAs(different)
이중 탭이요!!!!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorStockTest.java
> +                .doesNotThrowAnyException();
이중 탭..!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorStockTest.java
> +                .hasMessage("술 재고는 0 미만일 수 없습니다.");
이중 탭!!!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorStockTest.java
> +                () -> assertThat(origin).doesNotHaveSameHashCodeAs(different)
이중 탭!!!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorVolumeTest.java
> +                .doesNotThrowAnyException();
이중 탭..!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorVolumeTest.java
> +                .hasMessage("술 용량은 0 미만일 수 없습니다.");
이중 탭~~~!!!!

2023-08-19 14:53 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorVolumeTest.java
> +                () -> assertThat(origin).doesNotHaveSameHashCodeAs(different)
이중 탭! 이모탭! 이중 탭!

2023-08-19 15:46 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/core/liquor/domain/vo/LiquorAlcoholTest.java
> +                .hasMessage("술 도수는 0 이상 실수여야 합니다.");
종하요

2023-08-19 15:51 UTC, whatasame commented
내 작고 귀여운 13인치 16기가 메모리 MacBook Air M1이 귀여운 이중 탭으로 장난을 쳐놨구만

2023-08-20 05:29 UTC, whatasame commented
@hwihwi523 리뷰 반영 확인해주세요~

2023-08-22 07:18 UTC, hwihwi523 approved these changes
짱!!

2023-08-22 07:18 UTC, merged