feat: 장바구니 상품 등록
woowatechcamp/soolsool pull request #77
Opened 2023-08-19 14:42 UTC by hwihwi523

## ♻️ 변경 사항

### Cart 도메인 설계

1. 장바구니 상품을 관리하도록 설계했습니다.
2. 장바구니 상품을 DB에서 가져왔을 때 본인의 상품들인지 확인하는 로직을 구현했습니다.
3. 새로운 장바구니 상품을 추가할 때 검증 로직을 구현했습니다.

### 장바구니 상품 등록

1. 술 ID를 받아 장바구니 상품을 등록하는 기능을 구현했습니다~

<br>

## 📌 참고 사항

```
ex)
* 결제 부분 로직이 복잡한데, ~~~ 이유로 ~~~ 를 구현하기 위해 불가피했읍니다.
* ...
```

<br>

## 🎸 기타

```
ex) 닫을 이슈가 있다면,
closes #이슈번호
```
closes #59

2023-08-19 15:35 UTC, whatasame requested changes
고봉밥 한 그릇 드세요..

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/code/CartItemErrorCode.java
> +public enum CartItemErrorCode implements ErrorCode {
```suggestion
public enum CartErrorCode implements ErrorCode {
```

현재 패키지별로 ErrorCode를 구분하고 있어요. 근데 패키지 별로 구분하는 것도 복잡해서 클래스마다 구분해야할 것 같아요. 

`LiquorErrorCode` 보면 개행으로 구분하긴 했는데 복잡하쥬?

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/code/CartItemErrorCode.java
> +    ;
개행으로 Cart와 CartItem에서 발생하는 ErrorCode를 분류하는건 어떤가요?

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/controller/CartItemController.java
> +public class CartItemController {
```suggestion
@RestController
@RequestMapping("/cart-items")
@RequiredArgsConstructor
public class CartItemController {
```

순서가 불-편했는데 `MemberController` 슨배님은 이렇게 되어있더라구요.

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/controller/CartItemController.java
> +    }
```suggestion
        return ResponseEntity.status(HttpStatus.OK)
            .body(ApiResponse.from(CartItemResultCode.CART_ITEM_ADD_SUCCESS));
    }
```

CREATED는 Location 헤더를 넣어주는게 국룰이더라구요. 조회 API가 없어서 못 넣는다면 200으로~

>   The action performed by the POST method might not result in a  resource that can be identified by a URI. In this case, either 200 (OK) or 204 (No Content) is the appropriate response status, depending on whether or not the response includes an entity that describes the result.


전 키보드로 null을 치는 순간 폭발하는 프로그램을 만들고 싶어요.

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
>  public class Cart {
유사 일급 컬렉션인데 UnmodifiableList를 생성자나 Getter에서 생성해줬으면 좋겠어요.

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
> +    }
```suggestion
    private void validateMember(final Long memberId, final List<CartItem> cartItems) {
        if (cartItems.stream().anyMatch(cartItem -> cartItem.isSameMemberId(memberId))) {
            throw new SoolSoolException(CartItemErrorCode.NOT_EQUALS_MEMBER);
        }
    }
```

이 객체가 메시지를 알까요..

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
> +    }
```suggestion
    private void validateNull(final CartItem newCartItem) {
        if (Objects.isNull(newCartItem)) {
            throw new SoolSoolException(CartItemErrorCode.NULL_LIQUOR);
        }
    }
```

키보드에서 null을 입력하면 죄책감이 드는데 이건 어떤가요?

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
> +    }
```suggestion
    private void validateDuplicated(final CartItem newCartItem) {
        if (cartItems.stream().anyMatch(newCartItem::isSameWith)) {
            throw new SoolSoolException(CartItemErrorCode.EXISTS_CART_ITEM);
        }
    }
```

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
> +    }
```suggestion
    private void validateLiquorStatus(final CartItem newCartItem) {
        if (newCartItem.isStopped()) {
            throw new SoolSoolException(CartItemErrorCode.STOPPED_LIQUOR);
        }
    }
```

`Cart`에서 `Liquor` 정보를 아는 건 [디미터 법칙](https://github.com/whatasame/TIL/blob/main/stub/software-development-methodology/object-oriented-programming/%EB%94%94%EB%AF%B8%ED%84%B0%EC%9D%98%20%EB%B2%95%EC%B9%99(Law%20of%20Demeter).md) 위반 같은데 어떻게 생각하시나요?

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/CartItem.java
> +    }
```suggestion
    public boolean isSameLiquorWith(final CartItem other) {
        if (liquor == null || other.liquor == null) {
            return false;
        }

        return liquor.isSameWith(other.liquor);
    }
```

뭐가 같은 지 드러났으면 좋겠어요

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/dto/request/CartItemSaveRequest.java
> +    private final Integer quantity;
CartItemQuantity가 int인데 wrapper type을 쓰는 이유가 있나요? 

저는 primitive로 쓰는 편인데 다른 분들도 wrapper를 쓰시더라구요 궁금해요

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/repository/CartItemRepository.java
> +}
Spring data JPA 문법을 잘 쓰시네요.. 부럽다

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/service/CartItemService.java
> +        cart.addCartItem(newCartItem);
갑자기 든 생각인데 `Cart` 생성자에서 createdAt으로 정렬하는건 어떤가요? 현재는 들어오는 값에 따라 `Cart`가 정렬될 수도, 그렇지 않을 수도 있을 것 같네요.

DB에서 정렬하기 vs 메모리에서 정렬하기 둘 중에 뭐가 빠를까요? 궁금하당면

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/service/CartItemService.java
> +        cartItemRepository.save(newCartItem);
일단 Id 값을 반환하고 사용하는 쪽에서 안 쓰는건 어떤가요?

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/Liquor.java
> +    }
```java
@Entity
@Table(name = "liquors")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@EqualsAndHashCode(of = "id", callSuper = false)
public class Liquor extends BaseEntity {
```

이 코드 때문에 `equals()`로 똑같은 걸 할 수 있지 않나요?

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/Liquor.java
> +        final Long id,
만약에 DB에 1~100번이 있는데 실수로 개발자가 77번 짜리 `Liquor`를 임의로 생성해서 save하면 101번으로 저장되나요? 

아니면 77번 중복으로 예외가 터지나요?

2023-08-19 15:35 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/integration/repository/CartItemRepositoryTest.java
> +    }
data.sql을 사용하면 어떨까요?

2023-08-19 15:35 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/integration/repository/CartItemRepositoryTest.java
> +        liquor = liquorRepository.save(liquor);
인수 테스트가 아닌 `CartItem` 통합 테스트니까 `Liquor`은 그냥 바로 만들어도 되지 않을까요?

2023-08-19 15:35 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/integration/service/CartItemServiceTest.java
> +class CartItemServiceTest {
Import도 똑같이 되던데 혹시 다른게 뭐죠??? 아시면 알려주세요!! 궁금해

2023-08-19 15:35 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/integration/service/CartItemServiceTest.java
> +    private LiquorRepository liquorRepository;
단위 테스트가 아닌데 MockBean..?

2023-08-19 15:35 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/unit/domain/CartTest.java
> +        assertThrows(SoolSoolException.class, () -> new Cart(1L, cartItems));
```java
        assertThatThrownBy(() -> new MemberAddress(address))
                .isExactlyInstanceOf(SoolSoolException.class)
                .hasMessage("회원 주소는 100자보다 길 수 없습니다.");
```

이런 느낌으로 정확한 Exception과 메시지까지 검증하는건 어떤가요?

2023-08-19 15:35 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/Liquor.java
> +        final LiquorStatus status,
```java
private void validateIsNotNullableField(final Object... objects) {
    if (Arrays.stream(objects).anyMatch(Objects::isNull)) {
        throw new IllegalArgumentException("An object cannot be null");
    }
}
```

아까 낮에 보여줬던 방법으로 null이면 안되는 객체가 null인 경우를 검증하는 메서드를 만들면 어떨까요?

2023-08-19 15:40 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/code/CartItemErrorCode.java
> +public enum CartItemErrorCode implements ErrorCode {
우선 제안주신 코드대로 CartErrorCode로 명명했고, enum 원소들도 해당 오류코드를 던지는 코드마다 개행으로 구분했읍니다!

2023-08-19 15:42 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/controller/CartItemController.java
> +public class CartItemController {
LiquorController의 어노테이션도 해당 순서에 맞게 재구성했습니다!!

2023-08-19 15:44 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/controller/CartItemController.java
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 오 조회 API가 없을 경우 200으로 반환하는 컨벤션을 잊고 있었네요!!
그리고 Response의 from도 존재를 잊고 있었습니다!!
감사합니다!!
(null 폭발 프로그램은 좋은 것 같네여 ㅋㅋㅋㅋㅋㅋㅋㅋ)

2023-08-19 15:45 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
>  public class Cart {
오 일리가 있네요! 좋은 지적 감사합니다!!

2023-08-19 15:49 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
> +    }
아아.. 이것이 "메시지"군요..
hasDifferentMemberIdWith이라는 메시지를 던지는 메서드를 만들어 수정했읍니다!

2023-08-19 15:50 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
> +    }
오오 좋은 습관인 것 같습니다. 바로 학습 들어갑니다.

2023-08-19 15:51 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
> +    }
오 스트림이 지저분해 추출하여 사용했던 건데 한 줄로 충분히 직관적으로 표현할 수 있네요!!
바로 차용갑니다.

2023-08-19 15:52 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
> +    }
와방 굳입니다. hasStoppedLiquor() 메서드를 만들어 사용했읍니다!

2023-08-19 15:53 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/CartItem.java
> +    }
으음~~ 아주 좋습니다!
그리고 CartItem이 Liquor을 갖는 관계여서 has~ prefix로 변경하였습니다!

2023-08-19 15:54 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/repository/CartItemRepository.java
> +}
딱 저 부분만 압니다. 딱 저 부분만.

2023-08-19 16:16 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/service/CartItemService.java
> +        cart.addCartItem(newCartItem);
음 찾아 보니 뭐가 더 빠른지 명확하게 나와있진 않네요!

곰곰이 생각해 보니 저는 아래와 같은 이유에서 DB 정렬을 선택할 것 같습니다!
1. 직관적입니다.
    어플리케이션 단에서 정렬을 할 경우 로직이 추가되어 이해해야 할 코드가 증가하지만, DB에서 정렬하는 건 OrderBy 구문 하나로 이해가 가능하다 생각했습니다!
2. 추가 로직 구현이 필요 없습니다.
    이미 DB에서 지원하는 기능이다 보니, 추가 로직을 구현할 필요가 없습니다. 예시로, NPE를 직접 처리하면 훨씬 다채롭고 상황에 맞게 코드를 구성할 수 있지만 Optional API를 이용하는 것처럼 기존의 기능을 잘 활용하는 것은 중요하다 생각했습니다!

결론적으로 정렬 조건이 굉장히 복잡해진다면 어플리케이션 단에서 처리해야겠지만, 간단한 정렬의 경우 DB 정렬을 이용하는 게 직관성과 코드 간편화 측면에서 좋은 것 같습니다!

2023-08-19 16:20 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/service/CartItemService.java
> +        cartItemRepository.save(newCartItem);
음 좋습니다! 새로 생성되는 CartItem의 id를 얻을 수 있다는 걸 명시적으로 보여준다면 추후 기능 확장 시 더 빠른 이해가 가능하겠네요!

2023-08-19 16:21 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/Liquor.java
> +    }
아 그렇네요! 놓치고 있었습니다!!

2023-08-19 16:33 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/Liquor.java
> +        final Long id,
기존의 77번 데이터가 수정되는 것으로 알고 있습니다!

그런데 liquor id를 직접 지정해 주지 않으면 Cart 단위 테스트의 중복 상품 추가 테스트를 진행할 수 없습니다.

혹시 id를 직접 지정하지 않고 어떻게 해결할 수 있을까요??

2023-08-19 16:34 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/repository/CartItemRepositoryTest.java
> +    }
짱입니다..

2023-08-19 16:47 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/cart/dto/request/CartItemSaveRequest.java
> +    private final Integer quantity;
요청 데이터가 누락될 수 있기 때문에 dto에서는 null을 담을 수 있는 wrapper를 사용하는 편입니다!

2023-08-19 17:05 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/unit/domain/CartTest.java
> +        assertThrows(SoolSoolException.class, () -> new Cart(1L, cartItems));
오 좋네요!! CartErrorCode를 참조해서 동일한 메시지인지 검사하도록 수정했읍니다!!

2023-08-19 17:10 UTC, hwihwi523 commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/Liquor.java
> +        final LiquorStatus status,
오 이게 여기서 사용될 수 있군여!

감사히 잘쓰겠읍니다 핳핳

2023-08-19 17:38 UTC, hwihwi523 commented on src/test/java/com/woowacamp/soolsool/integration/service/CartItemServiceTest.java
> +class CartItemServiceTest {
정확히 몰라서 이번 계기로 검색을 해봤는데요!

@Import는 설정 파일 내에서 다른 설정 파일을 불러오기 위해 사용하고,
@ContextConfiguration은 테스트 클래스에서 사용할 컨텍스트의 설정 정보를 지정하는 데 사용된다고 하는 것 같습니다!

아직 제 스스로도 답변이 정확하지 않아 찝찝하긴 한데 일단 참고가 되실 수 있으니 링크 첨부해 봅니다!
https://stackoverflow.com/questions/48341097/import-vs-contextconfiguration-in-spring

2023-08-20 03:36 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/domain/Liquor.java
> +        final Long id,
```java
    @Test
    @DisplayName("새로운 장바구니 상품을 추가할 때 기존에 존재하는 상품이라면 예외를 던진다.")
    void duplicate() {
        // given
        CartItem mockCartItem = mock(CartItem.class);
        when(mockCartItem.hasSameLiquorWith(any())).thenReturn(true);

        List<CartItem> cartItems = new ArrayList<>(List.of(mockCartItem));

        Cart cart = new Cart(1L, cartItems);

        // when & then
        assertThatThrownBy(() -> cart.addCartItem(mockCartItem))
            .isExactlyInstanceOf(SoolSoolException.class)
            .hasMessage(CartErrorCode.EXISTS_CART_ITEM.getMessage());
    }
```

mocking은 신이다.

2023-08-20 03:41 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/dto/request/CartItemSaveRequest.java
> +    private final Integer quantity;
그럼 CartItem 저장 요청에 quantity 항목이 바디에 없으면 null이 되나요? 이 경우 NPE가 발생할 것 같아요.

반드시 필요한 항목이 없다면 요청을 시작조차 하지 않는게 적절할 것 같아요.

2023-08-20 03:42 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/service/CartItemService.java
> +        cart.addCartItem(newCartItem);
그럼 현재 `Cart`는 createdAt으로 정렬된 `CartItem`을 가질 수도, 그렇지 않을 수도 있는 도메인이네요.

지하철 노선처럼 항상 정렬된 상태를 유지할지, 그러지 않을 것인지 정책을 이야기 해봐야할 것 같아요.

2023-08-20 03:53 UTC, whatasame requested changes
고생하셨슴다! 반찬 모자랄까봐 누락된 사항이랑 취향 리뷰 조금 얹어 드렸어요

그리고 테스트가 터지는데 확인해주세요

2023-08-20 03:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/domain/Cart.java
>      }
```java
    private void validateDuplicated(final CartItem newCartItem) {
        if (cartItems.stream().anyMatch(newCartItem::hasSameLiquorWith)) {
            throw new SoolSoolException(CartErrorCode.EXISTS_CART_ITEM);
        }
    }
```

다른 곳에선 이렇게 사용하시던데 놓치신것 같아요

2023-08-20 03:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/cart/service/CartService.java
> +        return newCartItem.getId();
```suggestion
        return cartItemRepository.save(newCartItem).getId();
```

굳이 final을 없애지 않고 바로 반환해도 좋을 것 같아요.

final을 강제하다보니 어디서 변하는지 컴파일 단계에서 알 수 있어서 좋네요

2023-08-20 03:53 UTC, whatasame commented on src/main/java/com/woowacamp/soolsool/core/liquor/code/LiquorErrorCode.java
> +    INVALID_CATEGORY(NOT_FOUND.value(), "L107", "술 종류, 지역, 판매 상태가 존재하지 않습니다."),
```java
@Getter
@RequiredArgsConstructor
public enum GlobalErrorCode implements ErrorCode {

    NO_CONTENT(BAD_REQUEST.value(), "G101", "null일 수 없습니다."),
    ;
```

셋 다 없는 건지, 셋 중에 두 개가 없는 건지, 하나만 없는 건지 헷갈리네요. `GlobalErrorCode`에 이런게 있던데 이걸 사용하는 건 어떤가요?

2023-08-20 03:53 UTC, whatasame commented on src/test/java/com/woowacamp/soolsool/unit/domain/CartTest.java
> +            .hasMessage(CartErrorCode.NOT_EQUALS_MEMBER.getMessage());
```java
assertThatThrownBy(() -> new CartItemQuantity(quantity))
            .isExactlyInstanceOf(SoolSoolException.class)
            .hasMessage("장바구니 상품 수량은 1개 이상이어야 합니다.")
```

이 방법도 좋지만 `NOT_EQUALS_MEMBER`에 오타가 있거나 테스트에 오타가 있을 때 감지하지 못한다고 생각해서 예외 메시지는 직접 리터럴로 작성하는 편입니다. 취향이긴 해요!

2023-08-20 04:56 UTC, hwihwi523 commented
테스트 통과시키고 피드백 반영했는데 확인 부탁드립니다!!!!

2023-08-20 05:27 UTC, whatasame approved these changes
굿굿굿굿굿

2023-08-20 05:28 UTC, merged

2023-08-20 09:37 UTC, worldii commented
단순 궁금증인데요~! 내림차순은 조회때만 필요할 것 같은데, 조회를 할때는 어차피 fetchJoin을 써서 가져올 거 같은데 Add하는 과정 속에서도 내림 차순으로 가져온 이유가 있을까여?

2023-08-20 09:41 UTC, whatasame commented
```java
    @Transactional
    public Long saveCartItem(final Long memberId, final CartItemSaveRequest request) {
        final Liquor liquor = liquorRepository.findById(request.getLiquorId())
            .orElseThrow(() -> new SoolSoolException(CartErrorCode.NOT_FOUND_LIQUOR));

        CartItem newCartItem = CartItem.builder()
            .memberId(memberId)
            .liquor(liquor)
            .quantity(request.getQuantity())
            .build();

        final Cart cart = new Cart(memberId, findAllByMemberIdOrderByCreatedAtDesc(memberId));
        cart.addCartItem(newCartItem);

        return cartItemRepository.save(newCartItem).getId();
    }
```

이거 말하시는건가요? 저도 궁금하네요. 또, fetch join도 아니라 추가해야할 것 같은데 query가 복잡해질 것 같네요.